// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module ResetCounter

module b02(	// b02.scala:12:7
  input  clock,	// b02.scala:12:7
         reset,	// b02.scala:12:7
         io_LINEA,	// b02.scala:13:14
  output io_U	// b02.scala:13:14
);

  reg  [2:0] stato;	// b02.scala:28:22
  reg        U_reg;	// b02.scala:31:22
  wire       _GEN = stato == 3'h0;	// b02.scala:28:22, :35:17
  wire       _GEN_0 = stato == 3'h1;	// b02.scala:28:22, :35:17, :37:13
  wire       _GEN_1 = stato == 3'h2;	// b02.scala:28:22, :35:17, :42:15
  wire       _GEN_2 = stato == 3'h3;	// b02.scala:28:22, :35:17, :50:15
  wire       _GEN_3 = stato == 3'h4;	// b02.scala:28:22, :35:17, :57:13
  wire       _GEN_4 = stato == 3'h5;	// b02.scala:28:22, :35:17, :44:15
  wire       _GEN_5 = stato == 3'h6;	// b02.scala:28:22, :35:17, :52:15
  reg        hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire       hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// b02.scala:12:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  State_encoding3A_exactly_one_state_should_be_active:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     {1'h0, {1'h0, _GEN_5} + {1'h0, _GEN_4} + {1'h0, _GEN_3}}
                     + {1'h0, {1'h0, _GEN_2} + {1'h0, _GEN_1}}
                     + {1'h0, {1'h0, _GEN_0} + {1'h0, _GEN}} < 3'h2);	// b02.scala:12:7, :35:17, :42:15, :81:16, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire       _GEN_6 = _GEN_0 & U_reg;	// b02.scala:31:22, :35:17, :93:40
  Output_U_can_only_be_true_when_coming_from_StateE:
    assert property (@(posedge clock) disable iff (~hasBeenReset) ~U_reg | _GEN_6);	// b02.scala:31:22, :93:{12,19,40}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  From_StateE2C_next_state_must_be_StateB:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN_0);	// b02.scala:35:17, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  From_StateA2C_next_state_must_be_StateB:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN_0);	// b02.scala:35:17, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  From_StateD2C_next_state_must_be_StateE:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN_3);	// b02.scala:35:17, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  From_StateF2C_next_state_must_be_StateG:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN_5);	// b02.scala:35:17, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  From_StateB_with_LINEA3D02C_next_state_is_StateC:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN_0 & ~io_LINEA
                     |-> _GEN_1);	// b02.scala:35:17, :41:21, :111:34, src/main/scala/chisel3/ltl/LTL.scala:262:38, :321:32, :333:34, :362:39, :431:59
  From_StateB_with_LINEA3D12C_next_state_is_StateF:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN_0 & io_LINEA
                     |-> _GEN_4);	// b02.scala:35:17, :112:34, src/main/scala/chisel3/ltl/LTL.scala:262:38, :321:32, :333:34, :362:39, :431:59
  From_StateC_with_LINEA3D02C_next_state_is_StateD:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN_1 & ~io_LINEA
                     |-> _GEN_2);	// b02.scala:35:17, :41:21, :115:34, src/main/scala/chisel3/ltl/LTL.scala:262:38, :321:32, :333:34, :362:39, :431:59
  From_StateC_with_LINEA3D12C_next_state_is_StateG:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN_1 & io_LINEA
                     |-> _GEN_5);	// b02.scala:35:17, :116:34, src/main/scala/chisel3/ltl/LTL.scala:262:38, :321:32, :333:34, :362:39, :431:59
  From_StateG_with_LINEA3D02C_next_state_is_StateE:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN_5 & ~io_LINEA
                     |-> _GEN_3);	// b02.scala:35:17, :41:21, :119:34, src/main/scala/chisel3/ltl/LTL.scala:262:38, :321:32, :333:34, :362:39, :431:59
  From_StateG_with_LINEA3D12C_next_state_is_StateA:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN_5 & io_LINEA
                     |-> _GEN);	// b02.scala:35:17, :120:34, src/main/scala/chisel3/ltl/LTL.scala:262:38, :321:32, :333:34, :362:39, :431:59
  U_must_be_false_in_states_A2CC2CD2CF2CG_and_can_be_true_in_StateB:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     _GEN & ~U_reg & _GEN_6 & _GEN_1 & _GEN_2 & _GEN_4 & _GEN_5);	// b02.scala:31:22, :35:17, :93:{12,40}, :128:34, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  State_machine_should_eventually_reach_StateE:
    assert property (@(posedge clock) disable iff (~hasBeenReset) reset | stato != 3'h4
                     |-> ##[1:50] _GEN_3);	// b02.scala:28:22, :35:17, :57:13, :135:{35,45}, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// b02.scala:12:7
    if (reset) begin	// b02.scala:12:7
      hasBeenResetReg <= 1'h1;	// b02.scala:12:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
      stato <= 3'h0;	// b02.scala:28:22
      U_reg <= 1'h0;	// b02.scala:12:7, :31:22
    end
    else begin	// b02.scala:12:7
      automatic logic [7:0][2:0] _GEN_7;	// b02.scala:28:22, :35:17, :37:13, :41:34, :49:34, :57:13, :61:13, :65:13, :69:34
      _GEN_7 =
        {{stato},
         {{~io_LINEA, 2'h0}},
         {3'h6},
         {3'h1},
         {3'h4},
         {io_LINEA ? 3'h6 : 3'h3},
         {io_LINEA ? 3'h5 : 3'h2},
         {3'h1}};	// b02.scala:28:22, :35:17, :37:13, :41:{21,34}, :42:15, :44:15, :49:34, :50:15, :52:15, :57:13, :61:13, :65:13, :69:34, :70:15, :72:15, :81:16
      stato <= _GEN_7[stato];	// b02.scala:28:22, :35:17, :37:13, :41:34, :49:34, :57:13, :61:13, :65:13, :69:34
      U_reg <= ~(_GEN | _GEN_0 | _GEN_1 | _GEN_2) & (_GEN_3 | ~(_GEN_4 | _GEN_5) & U_reg);	// b02.scala:31:22, :35:17, :38:13, :46:13, :54:13, :58:13, :62:13, :66:13, :74:13
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// b02.scala:12:7
    `ifdef FIRRTL_BEFORE_INITIAL	// b02.scala:12:7
      `FIRRTL_BEFORE_INITIAL	// b02.scala:12:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// b02.scala:12:7
      automatic logic [31:0] _RANDOM[0:0];	// b02.scala:12:7
      `ifdef INIT_RANDOM_PROLOG_	// b02.scala:12:7
        `INIT_RANDOM_PROLOG_	// b02.scala:12:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// b02.scala:12:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// b02.scala:12:7
        stato = _RANDOM[/*Zero width*/ 1'b0][2:0];	// b02.scala:12:7, :28:22
        U_reg = _RANDOM[/*Zero width*/ 1'b0][3];	// b02.scala:12:7, :28:22, :31:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// b02.scala:12:7
      `FIRRTL_AFTER_INITIAL	// b02.scala:12:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  assign io_U = U_reg;	// b02.scala:12:7, :31:22
endmodule


// ----- 8< ----- FILE "./ResetCounter.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.1

module ResetCounter(
    input clk,
    input reset,
    output [31:0] timeSinceReset,
    output notChaos
);

reg [31:0] count;
reg flag;
initial begin
  count = 0;
  flag = 0;
end

assign timeSinceReset = count;
assign notChaos = flag;

always @(posedge clk) begin
    if (reset) begin
        count <= 0;
        flag <= 1;
    end else if (flag) begin
        count <= count + 1;
    end
end

endmodule
    

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----
