// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module ResetCounter

module CounterCell(	// counter.scala:7:7
  input  clock,	// counter.scala:7:7
         reset,	// counter.scala:7:7
         io_carry_in,	// counter.scala:8:14
  output io_carry_out,	// counter.scala:8:14
         io_value	// counter.scala:8:14
);

  reg  value;	// counter.scala:14:22
  wire io_carry_out_0 = value & io_carry_in;	// counter.scala:14:22, :16:25
  reg  hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// counter.scala:7:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  carry_out_should_equal_value_AND_carry_in:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// counter.scala:7:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg  REG;	// counter.scala:31:19
  value_should_toggle_when_carry_in_is_true2C_stay_stable_otherwise:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     REG == (io_carry_in ^ value));	// counter.scala:14:22, :30:23, :31:{19,27}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  value_output_should_equal_internal_register:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// counter.scala:7:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg  r;	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Delay.scala:11:20
  carry_out_should_be_stable_when_inputs_are_false:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(~io_carry_in & ~value) | io_carry_out_0 == r);	// counter.scala:14:22, :16:25, :30:37, :37:{19,20,33}, home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Delay.scala:11:20, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// counter.scala:7:7
    if (reset) begin	// counter.scala:7:7
      hasBeenResetReg <= 1'h1;	// counter.scala:7:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
      value <= 1'h0;	// counter.scala:7:7, :14:22
    end
    else	// counter.scala:7:7
      value <= io_carry_in ^ value;	// counter.scala:14:22, :20:22, :21:11
    REG <= value;	// counter.scala:14:22, :31:19
    r <= io_carry_out_0;	// counter.scala:16:25, home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Delay.scala:11:20
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// counter.scala:7:7
    `ifdef FIRRTL_BEFORE_INITIAL	// counter.scala:7:7
      `FIRRTL_BEFORE_INITIAL	// counter.scala:7:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// counter.scala:7:7
      automatic logic [31:0] _RANDOM[0:0];	// counter.scala:7:7
      `ifdef INIT_RANDOM_PROLOG_	// counter.scala:7:7
        `INIT_RANDOM_PROLOG_	// counter.scala:7:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// counter.scala:7:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// counter.scala:7:7
        value = _RANDOM[/*Zero width*/ 1'b0][0];	// counter.scala:7:7, :14:22
        REG = _RANDOM[/*Zero width*/ 1'b0][1];	// counter.scala:7:7, :14:22, :31:19
        r = _RANDOM[/*Zero width*/ 1'b0][2];	// counter.scala:7:7, :14:22, home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Delay.scala:11:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// counter.scala:7:7
      `FIRRTL_AFTER_INITIAL	// counter.scala:7:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  assign io_carry_out = io_carry_out_0;	// counter.scala:7:7, :16:25
  assign io_value = value;	// counter.scala:7:7, :14:22
endmodule

module Counter(	// counter.scala:40:7
  input  clock,	// counter.scala:40:7
         reset,	// counter.scala:40:7
  output io_out0,	// counter.scala:41:14
         io_out1,	// counter.scala:41:14
         io_out2	// counter.scala:41:14
);

  wire       _bit2_io_value;	// counter.scala:49:20
  wire       _bit1_io_carry_out;	// counter.scala:48:20
  wire       _bit1_io_value;	// counter.scala:48:20
  wire       _bit0_io_carry_out;	// counter.scala:47:20
  wire       _bit0_io_value;	// counter.scala:47:20
  wire [2:0] current_count = {_bit2_io_value, _bit1_io_value, _bit0_io_value};	// counter.scala:47:20, :48:20, :49:20, :69:26
  reg  [2:0] REG;	// counter.scala:72:38
  reg        hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire       hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// counter.scala:40:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  Counter_should_increment_by_1_each_cycle:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     current_count == REG + 3'h1);	// counter.scala:69:26, :72:{26,38,54}, :83:46, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg  [2:0] REG_1;	// counter.scala:75:48
  Counter_should_wrap_from_7_to_0:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(&current_count) | REG_1 == 3'h0);	// counter.scala:69:26, :75:{12,28,37,48,64}, :110:26, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Counter_value_should_never_exceed_7:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// counter.scala:40:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire       _GEN = current_count == 3'h0;	// counter.scala:69:26, :83:46, :110:26
  Counter_should_reach_value_0_within_8_cycles:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1 |-> ##[1:8] _GEN);	// counter.scala:40:7, :83:46, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  Counter_should_reach_value_1_within_8_cycles:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1 |-> ##[1:8]
                     current_count == 3'h1);	// counter.scala:40:7, :69:26, :83:46, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  Counter_should_reach_value_2_within_8_cycles:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1 |-> ##[1:8]
                     current_count == 3'h2);	// counter.scala:40:7, :69:26, :83:46, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  Counter_should_reach_value_3_within_8_cycles:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1 |-> ##[1:8]
                     current_count == 3'h3);	// counter.scala:40:7, :69:26, :83:46, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  Counter_should_reach_value_4_within_8_cycles:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1 |-> ##[1:8]
                     current_count == 3'h4);	// counter.scala:40:7, :69:26, :83:46, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  Counter_should_reach_value_5_within_8_cycles:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1 |-> ##[1:8]
                     current_count == 3'h5);	// counter.scala:40:7, :69:26, :83:46, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  Counter_should_reach_value_6_within_8_cycles:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1 |-> ##[1:8]
                     current_count == 3'h6);	// counter.scala:40:7, :69:26, :83:46, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  Counter_should_reach_value_7_within_8_cycles:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1 |-> ##[1:8]
                     &current_count);	// counter.scala:40:7, :69:26, :75:28, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  bit0_carry_in_should_always_be_true:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// counter.scala:40:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg        REG_2;	// counter.scala:88:19
  bit0_should_toggle_every_cycle:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     REG_2 == ~_bit0_io_value);	// counter.scala:47:20, :88:{19,35,39}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg        bit0_falling_REG;	// counter.scala:91:29
  reg        REG_3;	// counter.scala:92:37
  bit1_should_toggle_when_bit0_falls:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(bit0_falling_REG & ~_bit0_io_value) | REG_3 == ~_bit1_io_value);	// counter.scala:47:20, :48:20, :88:39, :91:{29,45}, :92:{12,26,37,53,57}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg        bit1_falling_REG;	// counter.scala:95:29
  reg        REG_4;	// counter.scala:96:37
  bit2_should_toggle_when_bit1_falls:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(bit1_falling_REG & ~_bit1_io_value) | REG_4 == ~_bit2_io_value);	// counter.scala:48:20, :49:20, :92:57, :95:{29,45}, :96:{12,26,37,53,57}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Counter_should_start_from_0_after_reset:
    assert property (@(posedge clock) disable iff (~hasBeenReset) reset | _GEN);	// counter.scala:83:46, :99:25, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg  [2:0] REG_5;	// counter.scala:102:36
  Counter_should_not_have_consecutive_same_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     reset | REG_5 != current_count);	// counter.scala:69:26, :102:{25,36,52}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  bit1_carry_in_should_equal_bit0_carry_out:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// counter.scala:40:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  bit2_carry_in_should_equal_bit1_carry_out:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// counter.scala:40:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg  [2:0] REG_6;	// counter.scala:111:19
  Counter_should_follow_binary_counting_pattern:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     REG_6 == ((&current_count)
                                 ? 3'h0
                                 : {_bit2_io_value, _bit1_io_value, _bit0_io_value}
                                   + 3'h1));	// counter.scala:47:20, :48:20, :49:20, :69:26, :75:28, :83:46, :110:{26,69}, :111:{19,35}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// counter.scala:40:7
    if (reset)	// src/main/scala/chisel3/ltl/LTL.scala:362:39
      hasBeenResetReg <= 1'h1;	// counter.scala:40:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
    REG <= current_count;	// counter.scala:69:26, :72:38
    REG_1 <= current_count;	// counter.scala:69:26, :75:48
    REG_2 <= _bit0_io_value;	// counter.scala:47:20, :88:19
    bit0_falling_REG <= _bit0_io_value;	// counter.scala:47:20, :91:29
    REG_3 <= _bit1_io_value;	// counter.scala:48:20, :92:37
    bit1_falling_REG <= _bit1_io_value;	// counter.scala:48:20, :95:29
    REG_4 <= _bit2_io_value;	// counter.scala:49:20, :96:37
    REG_5 <= current_count;	// counter.scala:69:26, :102:36
    REG_6 <= current_count;	// counter.scala:69:26, :111:19
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// counter.scala:40:7
    `ifdef FIRRTL_BEFORE_INITIAL	// counter.scala:40:7
      `FIRRTL_BEFORE_INITIAL	// counter.scala:40:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// counter.scala:40:7
      automatic logic [31:0] _RANDOM[0:0];	// counter.scala:40:7
      `ifdef INIT_RANDOM_PROLOG_	// counter.scala:40:7
        `INIT_RANDOM_PROLOG_	// counter.scala:40:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// counter.scala:40:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// counter.scala:40:7
        REG = _RANDOM[/*Zero width*/ 1'b0][2:0];	// counter.scala:40:7, :72:38
        REG_1 = _RANDOM[/*Zero width*/ 1'b0][5:3];	// counter.scala:40:7, :72:38, :75:48
        REG_2 = _RANDOM[/*Zero width*/ 1'b0][6];	// counter.scala:40:7, :72:38, :88:19
        bit0_falling_REG = _RANDOM[/*Zero width*/ 1'b0][7];	// counter.scala:40:7, :72:38, :91:29
        REG_3 = _RANDOM[/*Zero width*/ 1'b0][8];	// counter.scala:40:7, :72:38, :92:37
        bit1_falling_REG = _RANDOM[/*Zero width*/ 1'b0][9];	// counter.scala:40:7, :72:38, :95:29
        REG_4 = _RANDOM[/*Zero width*/ 1'b0][10];	// counter.scala:40:7, :72:38, :96:37
        REG_5 = _RANDOM[/*Zero width*/ 1'b0][13:11];	// counter.scala:40:7, :72:38, :102:36
        REG_6 = _RANDOM[/*Zero width*/ 1'b0][16:14];	// counter.scala:40:7, :72:38, :111:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// counter.scala:40:7
      `FIRRTL_AFTER_INITIAL	// counter.scala:40:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  CounterCell bit0 (	// counter.scala:47:20
    .clock        (clock),
    .reset        (reset),
    .io_carry_in  (1'h1),	// counter.scala:40:7
    .io_carry_out (_bit0_io_carry_out),
    .io_value     (_bit0_io_value)
  );
  CounterCell bit1 (	// counter.scala:48:20
    .clock        (clock),
    .reset        (reset),
    .io_carry_in  (_bit0_io_carry_out),	// counter.scala:47:20
    .io_carry_out (_bit1_io_carry_out),
    .io_value     (_bit1_io_value)
  );
  CounterCell bit2 (	// counter.scala:49:20
    .clock        (clock),
    .reset        (reset),
    .io_carry_in  (_bit1_io_carry_out),	// counter.scala:48:20
    .io_carry_out (/* unused */),
    .io_value     (_bit2_io_value)
  );
  assign io_out0 = _bit0_io_value;	// counter.scala:40:7, :47:20
  assign io_out1 = _bit1_io_value;	// counter.scala:40:7, :48:20
  assign io_out2 = _bit2_io_value;	// counter.scala:40:7, :49:20
endmodule


// ----- 8< ----- FILE "./ResetCounter.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.1

module ResetCounter(
    input clk,
    input reset,
    output [31:0] timeSinceReset,
    output notChaos
);

reg [31:0] count;
reg flag;
initial begin
  count = 0;
  flag = 0;
end

assign timeSinceReset = count;
assign notChaos = flag;

always @(posedge clk) begin
    if (reset) begin
        count <= 0;
        flag <= 1;
    end else if (flag) begin
        count <= count + 1;
    end
end

endmodule
    

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----
