// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module ResetCounter

module lock(	// lock.scala:7:7
  input        clock,	// lock.scala:7:7
               reset,	// lock.scala:7:7
               io_up,	// lock.scala:8:14
               io_down,	// lock.scala:8:14
  output       io_open,	// lock.scala:8:14
  output [4:0] io_position	// lock.scala:8:14
);

  reg  [4:0] position;	// lock.scala:16:25
  reg  [1:0] state;	// lock.scala:17:22
  reg        upReg;	// lock.scala:18:22
  reg        downReg;	// lock.scala:19:24
  wire       _GEN = state == 2'h2;	// lock.scala:7:7, :17:22, :33:17
  wire       _GEN_0 = position == 5'hF & upReg;	// lock.scala:16:25, :18:22, :49:{27,36}
  reg        hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire       hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// lock.scala:7:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  Position_should_not_exceed_31:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// lock.scala:7:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  State_should_be_within_valid_range_02D3:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// lock.scala:7:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg  [4:0] position_increased_REG;	// lock.scala:73:48
  reg  [4:0] position_increased_REG_1;	// lock.scala:73:80
  reg  [4:0] position_decreased_REG;	// lock.scala:74:48
  reg  [4:0] position_decreased_REG_1;	// lock.scala:74:80
  reg        REG;	// lock.scala:76:43
  reg        REG_1;	// lock.scala:76:62
  Position_should_only_increase_when_up_is_true_and_down_is_false:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     (position != position_increased_REG
                      & position > position_increased_REG_1) == (REG & ~REG_1));	// lock.scala:16:25, :73:{37,48,59,71,80}, :76:{31,43,51,54,62}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg        REG_2;	// lock.scala:78:43
  reg        REG_3;	// lock.scala:78:64
  Position_should_only_decrease_when_down_is_true_and_up_is_false:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     (position != position_decreased_REG
                      & position < position_decreased_REG_1) == (REG_2 & ~REG_3));	// lock.scala:16:25, :74:{37,48,59,71,80}, :78:{31,43,53,56,64}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Open_output_should_match_state_3:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// lock.scala:7:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg  [1:0] REG_4;	// lock.scala:85:19
  reg  [4:0] REG_5;	// lock.scala:85:64
  reg        REG_6;	// lock.scala:85:94
  Transition_from_state_0_to_1_should_only_happen_at_position_12_with_upReg:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     REG_4 == 2'h0 & state == 2'h1 == (REG_5 == 5'hC & REG_6));	// lock.scala:7:7, :17:22, :33:17, :35:21, :85:{19,27,35,52,64,75,84,94}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg  [1:0] REG_7;	// lock.scala:87:19
  reg  [4:0] REG_8;	// lock.scala:87:64
  reg        REG_9;	// lock.scala:87:94
  Transition_from_state_1_to_2_should_only_happen_at_position_21_with_downReg:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     REG_7 == 2'h1 & _GEN == (REG_8 == 5'h15 & REG_9));	// lock.scala:7:7, :33:17, :42:27, :87:{19,27,35,52,64,75,84,94}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg  [1:0] REG_10;	// lock.scala:89:19
  reg  [4:0] REG_11;	// lock.scala:89:64
  reg        REG_12;	// lock.scala:89:94
  Transition_from_state_2_to_3_should_only_happen_at_position_15_with_upReg:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     REG_10 == 2'h2 & (&state) == (REG_11 == 5'hF & REG_12));	// lock.scala:7:7, :17:22, :49:27, :61:20, :89:{19,27,35,52,64,75,84,94}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Should_reach_open_state_within_5_cycles_of_meeting_conditions:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN_0 & _GEN
                     |-> ##[1:5] &state);	// lock.scala:17:22, :33:17, :49:36, :61:20, :94:33, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// lock.scala:7:7
    if (reset) begin	// lock.scala:7:7
      hasBeenResetReg <= 1'h1;	// lock.scala:7:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
      position <= 5'h0;	// lock.scala:16:25
      state <= 2'h0;	// lock.scala:7:7, :17:22
      upReg <= 1'h0;	// lock.scala:7:7, :18:22
      downReg <= 1'h0;	// lock.scala:7:7, :19:24
    end
    else begin	// lock.scala:7:7
      automatic logic [3:0][1:0] _GEN_1;	// lock.scala:33:17, :35:40, :40:19, :47:21
      if (io_up & ~io_down)	// lock.scala:22:{14,17}
        position <= position + 5'h1;	// lock.scala:16:25, :23:26
      else if (io_down & ~io_up)	// lock.scala:24:{22,25}
        position <= position - 5'h1;	// lock.scala:16:25, :25:26
      _GEN_1 =
        {{(&state) & (upReg | downReg) ? 2'h0 : state},
         {downReg ? 2'h0 : _GEN_0 ? 2'h3 : state},
         {upReg ? 2'h0 : position == 5'h15 & downReg ? 2'h2 : state},
         {position == 5'hC & upReg ? 2'h1 : state}};	// lock.scala:7:7, :16:25, :17:22, :18:22, :19:24, :33:17, :35:{21,30,40}, :36:15, :40:19, :41:15, :42:{27,36,48}, :43:15, :47:21, :48:15, :49:{36,46}, :50:15, :54:{18,30}, :55:15
      state <= _GEN_1[state];	// lock.scala:17:22, :33:17, :35:40, :40:19, :47:21
      upReg <= io_up & ~io_down;	// lock.scala:18:22, :22:17, :29:18
      downReg <= io_down & ~io_up;	// lock.scala:19:24, :30:{22,25}
    end
    position_increased_REG <= position;	// lock.scala:16:25, :73:48
    position_increased_REG_1 <= position;	// lock.scala:16:25, :73:80
    position_decreased_REG <= position;	// lock.scala:16:25, :74:48
    position_decreased_REG_1 <= position;	// lock.scala:16:25, :74:80
    REG <= io_up;	// lock.scala:76:43
    REG_1 <= io_down;	// lock.scala:76:62
    REG_2 <= io_down;	// lock.scala:78:43
    REG_3 <= io_up;	// lock.scala:78:64
    REG_4 <= state;	// lock.scala:17:22, :85:19
    REG_5 <= position;	// lock.scala:16:25, :85:64
    REG_6 <= upReg;	// lock.scala:18:22, :85:94
    REG_7 <= state;	// lock.scala:17:22, :87:19
    REG_8 <= position;	// lock.scala:16:25, :87:64
    REG_9 <= downReg;	// lock.scala:19:24, :87:94
    REG_10 <= state;	// lock.scala:17:22, :89:19
    REG_11 <= position;	// lock.scala:16:25, :89:64
    REG_12 <= upReg;	// lock.scala:18:22, :89:94
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// lock.scala:7:7
    `ifdef FIRRTL_BEFORE_INITIAL	// lock.scala:7:7
      `FIRRTL_BEFORE_INITIAL	// lock.scala:7:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// lock.scala:7:7
      automatic logic [31:0] _RANDOM[0:1];	// lock.scala:7:7
      `ifdef INIT_RANDOM_PROLOG_	// lock.scala:7:7
        `INIT_RANDOM_PROLOG_	// lock.scala:7:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// lock.scala:7:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// lock.scala:7:7
        end	// lock.scala:7:7
        position = _RANDOM[1'h0][4:0];	// lock.scala:7:7, :16:25
        state = _RANDOM[1'h0][6:5];	// lock.scala:7:7, :16:25, :17:22
        upReg = _RANDOM[1'h0][7];	// lock.scala:7:7, :16:25, :18:22
        downReg = _RANDOM[1'h0][8];	// lock.scala:7:7, :16:25, :19:24
        position_increased_REG = _RANDOM[1'h0][13:9];	// lock.scala:7:7, :16:25, :73:48
        position_increased_REG_1 = _RANDOM[1'h0][18:14];	// lock.scala:7:7, :16:25, :73:80
        position_decreased_REG = _RANDOM[1'h0][23:19];	// lock.scala:7:7, :16:25, :74:48
        position_decreased_REG_1 = _RANDOM[1'h0][28:24];	// lock.scala:7:7, :16:25, :74:80
        REG = _RANDOM[1'h0][29];	// lock.scala:7:7, :16:25, :76:43
        REG_1 = _RANDOM[1'h0][30];	// lock.scala:7:7, :16:25, :76:62
        REG_2 = _RANDOM[1'h0][31];	// lock.scala:7:7, :16:25, :78:43
        REG_3 = _RANDOM[1'h1][0];	// lock.scala:7:7, :78:64
        REG_4 = _RANDOM[1'h1][2:1];	// lock.scala:7:7, :78:64, :85:19
        REG_5 = _RANDOM[1'h1][7:3];	// lock.scala:7:7, :78:64, :85:64
        REG_6 = _RANDOM[1'h1][8];	// lock.scala:7:7, :78:64, :85:94
        REG_7 = _RANDOM[1'h1][10:9];	// lock.scala:7:7, :78:64, :87:19
        REG_8 = _RANDOM[1'h1][15:11];	// lock.scala:7:7, :78:64, :87:64
        REG_9 = _RANDOM[1'h1][16];	// lock.scala:7:7, :78:64, :87:94
        REG_10 = _RANDOM[1'h1][18:17];	// lock.scala:7:7, :78:64, :89:19
        REG_11 = _RANDOM[1'h1][23:19];	// lock.scala:7:7, :78:64, :89:64
        REG_12 = _RANDOM[1'h1][24];	// lock.scala:7:7, :78:64, :89:94
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// lock.scala:7:7
      `FIRRTL_AFTER_INITIAL	// lock.scala:7:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  assign io_open = &state;	// lock.scala:7:7, :17:22, :61:20
  assign io_position = position;	// lock.scala:7:7, :16:25
endmodule

module TestTop(	// lock.scala:102:7
  input        clock,	// lock.scala:102:7
               reset,	// lock.scala:102:7
               io_up,	// lock.scala:103:14
               io_down,	// lock.scala:103:14
  output       io_open,	// lock.scala:103:14
  output [4:0] io_position	// lock.scala:103:14
);

  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  lock dut (	// lock.scala:110:19
    .clock       (clock),
    .reset       (reset),
    .io_up       (io_up),
    .io_down     (io_down),
    .io_open     (io_open),
    .io_position (io_position)
  );
endmodule


// ----- 8< ----- FILE "./ResetCounter.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.1

module ResetCounter(
    input clk,
    input reset,
    output [31:0] timeSinceReset,
    output notChaos
);

reg [31:0] count;
reg flag;
initial begin
  count = 0;
  flag = 0;
end

assign timeSinceReset = count;
assign notChaos = flag;

always @(posedge clk) begin
    if (reset) begin
        count <= 0;
        flag <= 1;
    end else if (flag) begin
        count <= count + 1;
    end
end

endmodule
    

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----
