// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module ResetCounter

module philosopher(	// drop4.scala:15:7
  input        clock,	// drop4.scala:15:7
               reset,	// drop4.scala:15:7
  output [1:0] io_out,	// drop4.scala:16:14
  input  [1:0] io_left,	// drop4.scala:16:14
               io_right,	// drop4.scala:16:14
               io_init	// drop4.scala:16:14
);

  reg  [1:0]  state;	// drop4.scala:23:22
  reg  [31:0] lfsr;	// drop4.scala:27:21
  wire        _GEN = state == 2'h1;	// drop4.scala:15:7, :23:22, :34:17
  wire        _GEN_0 = io_left == 2'h0;	// drop4.scala:15:7, :36:20
  wire        _GEN_1 = state == 2'h0;	// drop4.scala:15:7, :23:22, :34:17
  wire        _GEN_2 = state == 2'h2;	// drop4.scala:15:7, :23:22, :34:17
  wire        _GEN_3 = (&state) & io_left != 2'h2 & io_right != 2'h3 & io_right != 2'h2;	// drop4.scala:15:7, :23:22, :34:17, :46:15, :57:21, :58:22, :59:{22,45}, :60:15
  reg         hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire        hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// drop4.scala:15:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  Invalid_state_detected:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     _GEN_1 | _GEN | _GEN_2 | (&state));	// drop4.scala:23:22, :34:17, :70:39, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Left_neighbor_eating_simultaneously:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_GEN_2 & io_left == 2'h2));	// drop4.scala:15:7, :34:17, :74:{12,41,52}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Right_neighbor_eating_simultaneously:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_GEN_2 & io_right == 2'h2));	// drop4.scala:15:7, :34:17, :76:{12,41,53}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  READING_should_transition_to_THINKING_when_left_is_THINKING:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN & _GEN_0
                     |-> _GEN_1);	// drop4.scala:34:17, :36:20, :80:45, src/main/scala/chisel3/ltl/LTL.scala:262:38, :321:32, :333:34, :362:39, :431:59
  HUNGRY_should_transition_to_EATING_when_conditions_are_satisfied:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN_3 |-> _GEN_2);	// drop4.scala:23:22, :34:17, :59:45, :60:15, src/main/scala/chisel3/ltl/LTL.scala:262:38, :321:32, :333:34, :362:39, :431:59
  Hungry_philosopher_should_eventually_eat:
    assert property (@(posedge clock) disable iff (~hasBeenReset) &state |-> ##[1:100]
                     _GEN_2);	// drop4.scala:23:22, :34:17, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// drop4.scala:15:7
    if (reset) begin	// drop4.scala:15:7
      hasBeenResetReg <= 1'h1;	// drop4.scala:15:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
      state <= io_init;	// drop4.scala:23:22
      lfsr <= 32'h1;	// drop4.scala:27:21
    end
    else begin	// drop4.scala:15:7
      automatic logic [3:0][1:0] _GEN_4;	// drop4.scala:34:17, :36:44, :41:54, :50:18
      _GEN_4 =
        {{_GEN_3 ? 2'h2 : state},
         {{~(lfsr[0]), 1'h0}},
         {_GEN_0 ? 2'h0 : state},
         {lfsr[0] & io_right == 2'h1 ? 2'h1 : lfsr[0] ? 2'h0 : 2'h3}};	// drop4.scala:15:7, :23:22, :27:21, :28:18, :34:17, :36:{20,44}, :37:15, :41:{17,30,54}, :42:15, :43:24, :44:15, :46:15, :50:18, :51:15, :53:15, :59:45, :60:15
      state <= _GEN_4[state];	// drop4.scala:23:22, :34:17, :36:44, :41:54, :50:18
      lfsr <= {lfsr[30:0], lfsr[31] ^ lfsr[21] ^ lfsr[1] ^ lfsr[0]};	// drop4.scala:27:21, :28:18, :29:{8,31,42,53,57}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// drop4.scala:15:7
    `ifdef FIRRTL_BEFORE_INITIAL	// drop4.scala:15:7
      `FIRRTL_BEFORE_INITIAL	// drop4.scala:15:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// drop4.scala:15:7
      automatic logic [31:0] _RANDOM[0:1];	// drop4.scala:15:7
      `ifdef INIT_RANDOM_PROLOG_	// drop4.scala:15:7
        `INIT_RANDOM_PROLOG_	// drop4.scala:15:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// drop4.scala:15:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// drop4.scala:15:7
        end	// drop4.scala:15:7
        state = _RANDOM[1'h0][1:0];	// drop4.scala:15:7, :23:22
        lfsr = {_RANDOM[1'h0][31:2], _RANDOM[1'h1][1:0]};	// drop4.scala:15:7, :23:22, :27:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// drop4.scala:15:7
      `FIRRTL_AFTER_INITIAL	// drop4.scala:15:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  assign io_out = state;	// drop4.scala:15:7, :23:22
endmodule

module philo4(	// drop4.scala:99:7
  input        clock,	// drop4.scala:99:7
               reset,	// drop4.scala:99:7
  output [1:0] io_st0,	// drop4.scala:100:14
               io_st1,	// drop4.scala:100:14
               io_st2,	// drop4.scala:100:14
               io_st3	// drop4.scala:100:14
);

  wire [1:0] _ph3_io_out;	// drop4.scala:114:19
  wire [1:0] _ph2_io_out;	// drop4.scala:113:19
  wire [1:0] _ph1_io_out;	// drop4.scala:112:19
  wire [1:0] _ph0_io_out;	// drop4.scala:111:19
  wire       eatingStates_0 = _ph0_io_out == 2'h2;	// drop4.scala:111:19, :145:37
  wire       eatingStates_1 = _ph1_io_out == 2'h2;	// drop4.scala:112:19, :145:37, :146:37
  wire       eatingStates_2 = _ph2_io_out == 2'h2;	// drop4.scala:113:19, :145:37, :147:37
  wire       eatingStates_3 = _ph3_io_out == 2'h2;	// drop4.scala:114:19, :145:37, :148:37
  reg        hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  always @(posedge clock) begin	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    if (reset)	// src/main/scala/chisel3/ltl/LTL.scala:362:39
      hasBeenResetReg <= 1'h1;	// drop4.scala:149:14, src/main/scala/chisel3/ltl/LTL.scala:362:39
  end // always @(posedge)
  wire       hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// drop4.scala:149:14, src/main/scala/chisel3/ltl/LTL.scala:362:39
  More_than_one_philosopher_eating_simultaneously:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     {1'h0, {1'h0, eatingStates_0} + {1'h0, eatingStates_1}}
                     + {1'h0, {1'h0, eatingStates_2} + {1'h0, eatingStates_3}} < 3'h2);	// drop4.scala:145:37, :146:37, :147:37, :148:37, :149:14, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  System_should_not_deadlock_when_all_philosophers_are_hungry:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     (&_ph0_io_out) & (&_ph1_io_out) & (&_ph2_io_out) & (&_ph3_io_out)
                     |-> ##[1:50]
                     eatingStates_0 | eatingStates_1 | eatingStates_2 | eatingStates_3);	// drop4.scala:111:19, :112:19, :113:19, :114:19, :145:37, :146:37, :147:37, :148:37, :152:31, :153:31, :154:{31,53}, :155:31, :161:56, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  Philosopher_0_should_eventually_eat_when_hungry:
    assert property (@(posedge clock) disable iff (~hasBeenReset) &_ph0_io_out
                     |-> ##[1:200] eatingStates_0);	// drop4.scala:111:19, :145:37, :152:31, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  Philosopher_1_should_eventually_eat_when_hungry:
    assert property (@(posedge clock) disable iff (~hasBeenReset) &_ph1_io_out
                     |-> ##[1:200] eatingStates_1);	// drop4.scala:112:19, :146:37, :153:31, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  Philosopher_2_should_eventually_eat_when_hungry:
    assert property (@(posedge clock) disable iff (~hasBeenReset) &_ph2_io_out
                     |-> ##[1:200] eatingStates_2);	// drop4.scala:113:19, :147:37, :154:31, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  Philosopher_3_should_eventually_eat_when_hungry:
    assert property (@(posedge clock) disable iff (~hasBeenReset) &_ph3_io_out
                     |-> ##[1:200] eatingStates_3);	// drop4.scala:114:19, :148:37, :155:31, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  Invalid_philosopher_state_detected:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     (_ph0_io_out == 2'h0 | _ph0_io_out == 2'h1 | _ph0_io_out == 2'h2
                      | (&_ph0_io_out))
                     & (_ph1_io_out == 2'h0 | _ph1_io_out == 2'h1 | _ph1_io_out == 2'h2
                        | (&_ph1_io_out))
                     & (_ph2_io_out == 2'h0 | _ph2_io_out == 2'h1 | _ph2_io_out == 2'h2
                        | (&_ph2_io_out))
                     & (_ph3_io_out == 2'h0 | _ph3_io_out == 2'h1 | _ph3_io_out == 2'h2
                        | (&_ph3_io_out)));	// drop4.scala:111:19, :112:19, :113:19, :114:19, :119:15, :124:15, :145:37, :185:{20,53}, :186:{20,41,51}, :187:{20,53}, :188:{20,41,51}, :189:{20,53}, :190:{20,41,51,73}, :191:{20,53}, :192:{20,41,51}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  philosopher ph0 (	// drop4.scala:111:19
    .clock    (clock),
    .reset    (reset),
    .io_out   (_ph0_io_out),
    .io_left  (_ph3_io_out),	// drop4.scala:114:19
    .io_right (_ph1_io_out),	// drop4.scala:112:19
    .io_init  (2'h1)	// drop4.scala:119:15
  );
  philosopher ph1 (	// drop4.scala:112:19
    .clock    (clock),
    .reset    (reset),
    .io_out   (_ph1_io_out),
    .io_left  (_ph0_io_out),	// drop4.scala:111:19
    .io_right (_ph2_io_out),	// drop4.scala:113:19
    .io_init  (2'h0)	// drop4.scala:124:15
  );
  philosopher ph2 (	// drop4.scala:113:19
    .clock    (clock),
    .reset    (reset),
    .io_out   (_ph2_io_out),
    .io_left  (_ph1_io_out),	// drop4.scala:112:19
    .io_right (_ph3_io_out),	// drop4.scala:114:19
    .io_init  (2'h0)	// drop4.scala:124:15
  );
  philosopher ph3 (	// drop4.scala:114:19
    .clock    (clock),
    .reset    (reset),
    .io_out   (_ph3_io_out),
    .io_left  (_ph2_io_out),	// drop4.scala:113:19
    .io_right (_ph0_io_out),	// drop4.scala:111:19
    .io_init  (2'h0)	// drop4.scala:124:15
  );
  assign io_st0 = _ph0_io_out;	// drop4.scala:99:7, :111:19
  assign io_st1 = _ph1_io_out;	// drop4.scala:99:7, :112:19
  assign io_st2 = _ph2_io_out;	// drop4.scala:99:7, :113:19
  assign io_st3 = _ph3_io_out;	// drop4.scala:99:7, :114:19
endmodule


// ----- 8< ----- FILE "./ResetCounter.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.1

module ResetCounter(
    input clk,
    input reset,
    output [31:0] timeSinceReset,
    output notChaos
);

reg [31:0] count;
reg flag;
initial begin
  count = 0;
  flag = 0;
end

assign timeSinceReset = count;
assign notChaos = flag;

always @(posedge clk) begin
    if (reset) begin
        count <= 0;
        flag <= 1;
    end else if (flag) begin
        count <= count + 1;
    end
end

endmodule
    

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----
