// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// external module ResetCounter

module sender(	// abp.scala:127:7
  input        clock,	// abp.scala:127:7
               reset,	// abp.scala:127:7
  input  [1:0] io_ack,	// abp.scala:128:14
  input        io_active,	// abp.scala:128:14
  output [2:0] io_message,	// abp.scala:128:14
  output       io_sndmsg,	// abp.scala:128:14
  output [2:0] io_state	// abp.scala:128:14
);

  reg  [2:0]  state;	// abp.scala:136:22
  reg  [2:0]  messageReg;	// abp.scala:137:27
  reg         exit1;	// abp.scala:138:22
  reg  [1:0]  smsg;	// abp.scala:139:21
  reg  [15:0] lfsr;	// abp.scala:142:21
  wire        _io_sndmsg_T_1 = state == 3'h3;	// abp.scala:136:22, :137:27, :150:57
  wire        _GEN = state == 3'h1;	// abp.scala:136:22, :148:24, :156:52
  wire        _GEN_0 = state == 3'h2;	// abp.scala:136:22, :145:24, :157:11
  wire        _GEN_1 = state == 3'h4;	// abp.scala:136:22, :145:24, :158:11
  wire        _GEN_2 = state == 3'h5;	// abp.scala:136:22, :158:45
  reg         hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire        hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// abp.scala:127:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  Sender_state_should_be_valid:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(|state) | _GEN | _GEN_0 | _io_sndmsg_T_1 | _GEN_1 | _GEN_2);	// abp.scala:136:22, :150:{23,57}, :156:52, :157:11, :158:{11,36,45}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire        _GEN_3 = messageReg == 3'h4;	// abp.scala:137:27, :145:24, :164:61
  SEND0_with_smsg3DONE_should_send_DATA10_or_DERR:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     messageReg == 3'h2 | _GEN_3);	// abp.scala:137:27, :145:24, :164:{25,47,61}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  SEND0_with_smsg3DZERO_should_send_DATA00_or_DERR:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     messageReg == 3'h0 | _GEN_3);	// abp.scala:136:22, :137:27, :164:61, :169:{25,47}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  SEND1_with_smsg3DONE_should_send_DATA11_or_DERR:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     messageReg == 3'h3 | _GEN_3);	// abp.scala:137:27, :164:61, :174:{25,47}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  SEND1_with_smsg3DZERO_should_send_DATA01_or_DERR:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     messageReg == 3'h1 | _GEN_3);	// abp.scala:137:27, :148:24, :164:61, :179:{25,47}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire        _GEN_4 = _GEN_0 & exit1;	// abp.scala:138:22, :157:11, :184:45
  wire        _GEN_5 = _GEN_2 & exit1;	// abp.scala:138:22, :158:45, :284:54
  wire [2:0]  nextState = _GEN_4 ? 3'h3 : _GEN_5 ? 3'h0 : state;	// abp.scala:136:22, :137:27, :184:45, :280:15, :282:57, :283:17, :284:{54,63}, :285:17
  WAIT0_with_exit1_should_transition_to_INIT1:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_GEN_4 & nextState != 3'h3));	// abp.scala:137:27, :184:{12,45,54,91}, :282:57, :283:17, :284:63, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  WAIT1_with_exit1_should_transition_to_INIT0:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_GEN_5 & (|nextState)));	// abp.scala:187:{12,54,91}, :282:57, :283:17, :284:{54,63}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// abp.scala:127:7
    if (reset) begin	// abp.scala:127:7
      hasBeenResetReg <= 1'h1;	// abp.scala:127:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
      state <= 3'h0;	// abp.scala:136:22
      messageReg <= 3'h3;	// abp.scala:137:27
      exit1 <= 1'h0;	// abp.scala:127:7, :138:22
      smsg <= 2'h2;	// abp.scala:139:21
      lfsr <= 16'h1;	// abp.scala:142:21
    end
    else begin	// abp.scala:127:7
      automatic logic _GEN_6;	// abp.scala:191:19
      _GEN_6 = state == 3'h3;	// abp.scala:136:22, :137:27, :191:19
      if (io_active) begin	// abp.scala:128:14
        automatic logic [1:0] _GEN_7;	// abp.scala:194:22, :195:16, :197:16
        _GEN_7 = {1'h0, lfsr[0]};	// abp.scala:127:7, :142:21, :144:20, :194:22, :195:16, :197:16
        if (|state) begin	// abp.scala:136:22, :150:23
          if (_GEN)	// abp.scala:156:52
            state <= 3'h2;	// abp.scala:136:22, :145:24
          else if (_GEN_0) begin	// abp.scala:157:11
            if (exit1) begin	// abp.scala:138:22
              state <= 3'h3;	// abp.scala:136:22, :137:27
              smsg <= 2'h2;	// abp.scala:139:21
            end
          end
          else if (_GEN_6) begin	// abp.scala:191:19
            state <= 3'h4;	// abp.scala:136:22, :145:24
            smsg <= _GEN_7;	// abp.scala:139:21, :194:22, :195:16, :197:16
          end
          else begin	// abp.scala:191:19
            automatic logic _GEN_8;	// abp.scala:136:22, :191:19, :251:22
            _GEN_8 = _GEN_2 & exit1;	// abp.scala:136:22, :138:22, :158:45, :191:19, :251:22
            if (_GEN_1)	// abp.scala:158:11
              state <= 3'h5;	// abp.scala:136:22, :158:45
            else if (_GEN_8)	// abp.scala:136:22, :191:19, :251:22
              state <= 3'h0;	// abp.scala:136:22
            if (_GEN_1 | ~_GEN_8) begin	// abp.scala:136:22, :139:21, :158:11, :191:19, :251:22
            end
            else	// abp.scala:139:21, :191:19
              smsg <= 2'h2;	// abp.scala:139:21
          end
        end
        else begin	// abp.scala:150:23
          state <= 3'h1;	// abp.scala:136:22, :148:24
          smsg <= _GEN_7;	// abp.scala:139:21, :194:22, :195:16, :197:16
        end
        exit1 <=
          (|state)
          & (_GEN
               ? exit1
               : _GEN_0
                   ? ~exit1 & io_ack == 2'h0 | exit1
                   : ~_GEN_6 & (~_GEN_1 & _GEN_2 & ~exit1 & io_ack == 2'h1 | exit1));	// abp.scala:136:22, :138:22, :150:23, :156:52, :157:11, :158:{11,45}, :163:48, :168:48, :191:19, :193:15, :210:{14,22}, :211:26, :212:39, :234:15
      end
      if (io_active & (|state)) begin	// abp.scala:136:22, :137:27, :150:23, :190:19, :191:19
        automatic logic [2:0] r10_message;	// abp.scala:145:24
        automatic logic [2:0] r00_message;	// abp.scala:146:24
        automatic logic       _GEN_9;	// abp.scala:202:22
        automatic logic       _GEN_10;	// abp.scala:202:22
        automatic logic       _GEN_11;	// abp.scala:202:22
        r10_message = lfsr[1] ? 3'h2 : 3'h4;	// abp.scala:142:21, :145:{24,29}
        r00_message = {~(lfsr[2]), 2'h0};	// abp.scala:142:21, :146:{24,29}, :168:48
        _GEN_9 = smsg == 2'h1;	// abp.scala:139:21, :163:48, :202:22
        _GEN_10 = smsg == 2'h0;	// abp.scala:139:21, :168:48, :202:22
        _GEN_11 = smsg == 2'h2;	// abp.scala:139:21, :202:22
        if (_GEN) begin	// abp.scala:156:52
          if (_GEN_9)	// abp.scala:202:22
            messageReg <= r10_message;	// abp.scala:137:27, :145:24
          else if (_GEN_10)	// abp.scala:202:22
            messageReg <= r00_message;	// abp.scala:137:27, :146:24
          else if (_GEN_11)	// abp.scala:202:22
            messageReg <= 3'h4;	// abp.scala:137:27, :145:24
        end
        else begin	// abp.scala:156:52
          automatic logic [2:0] _GEN_12;	// abp.scala:137:27, :202:22, :205:41
          _GEN_12 = _GEN_11 ? 3'h4 : messageReg;	// abp.scala:137:27, :145:24, :202:22, :205:41
          if (_GEN_0) begin	// abp.scala:157:11
            if (exit1) begin	// abp.scala:138:22
            end
            else begin	// abp.scala:138:22
              automatic logic [2:0]      _GEN_13;	// abp.scala:202:22, :203:43
              automatic logic [3:0][2:0] _GEN_14;	// abp.scala:137:27, :211:26, :214:28
              _GEN_13 = _GEN_9 ? r10_message : _GEN_10 ? r00_message : _GEN_12;	// abp.scala:137:27, :145:24, :146:24, :202:22, :203:43, :204:44, :205:41
              _GEN_14 = {{messageReg}, {_GEN_13}, {_GEN_13}, {messageReg}};	// abp.scala:137:27, :202:22, :203:43, :211:26, :214:28
              messageReg <= _GEN_14[io_ack];	// abp.scala:137:27, :211:26, :214:28
            end
          end
          else if (~_GEN_6) begin	// abp.scala:191:19, :234:15
            automatic logic [2:0] r11_message;	// abp.scala:147:24
            automatic logic [2:0] r01_message;	// abp.scala:148:24
            r11_message = lfsr[3] ? 3'h3 : 3'h4;	// abp.scala:137:27, :142:21, :145:24, :147:{24,29}
            r01_message = lfsr[4] ? 3'h1 : 3'h4;	// abp.scala:142:21, :145:24, :148:{24,29}
            if (_GEN_1) begin	// abp.scala:158:11
              if (_GEN_9)	// abp.scala:202:22
                messageReg <= r11_message;	// abp.scala:137:27, :147:24
              else if (_GEN_10)	// abp.scala:202:22
                messageReg <= r01_message;	// abp.scala:137:27, :148:24
              else if (_GEN_11)	// abp.scala:202:22
                messageReg <= 3'h4;	// abp.scala:137:27, :145:24
            end
            else if (_GEN_2 & ~exit1) begin	// abp.scala:137:27, :138:22, :158:45, :191:19, :210:14, :251:22, :252:26
              automatic logic [2:0]      _GEN_15;	// abp.scala:243:22, :244:43
              automatic logic [3:0][2:0] _GEN_16;	// abp.scala:137:27, :211:26, :252:26, :255:28
              _GEN_15 = _GEN_9 ? r11_message : _GEN_10 ? r01_message : _GEN_12;	// abp.scala:137:27, :147:24, :148:24, :202:22, :205:41, :243:22, :244:43, :245:44
              _GEN_16 = {{messageReg}, {_GEN_15}, {messageReg}, {_GEN_15}};	// abp.scala:137:27, :211:26, :243:22, :244:43, :252:26, :255:28
              messageReg <= _GEN_16[io_ack];	// abp.scala:137:27, :211:26, :252:26, :255:28
            end
          end
        end
      end
      lfsr <= {lfsr[14:0], lfsr[15] ^ lfsr[13] ^ lfsr[12] ^ lfsr[10]};	// abp.scala:142:21, :143:{14,19,31,42,53,58,64}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// abp.scala:127:7
    `ifdef FIRRTL_BEFORE_INITIAL	// abp.scala:127:7
      `FIRRTL_BEFORE_INITIAL	// abp.scala:127:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// abp.scala:127:7
      automatic logic [31:0] _RANDOM[0:0];	// abp.scala:127:7
      `ifdef INIT_RANDOM_PROLOG_	// abp.scala:127:7
        `INIT_RANDOM_PROLOG_	// abp.scala:127:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// abp.scala:127:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// abp.scala:127:7
        state = _RANDOM[/*Zero width*/ 1'b0][2:0];	// abp.scala:127:7, :136:22
        messageReg = _RANDOM[/*Zero width*/ 1'b0][5:3];	// abp.scala:127:7, :136:22, :137:27
        exit1 = _RANDOM[/*Zero width*/ 1'b0][6];	// abp.scala:127:7, :136:22, :138:22
        smsg = _RANDOM[/*Zero width*/ 1'b0][8:7];	// abp.scala:127:7, :136:22, :139:21
        lfsr = _RANDOM[/*Zero width*/ 1'b0][24:9];	// abp.scala:127:7, :136:22, :142:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// abp.scala:127:7
      `FIRRTL_AFTER_INITIAL	// abp.scala:127:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  assign io_message = messageReg;	// abp.scala:127:7, :137:27
  assign io_sndmsg = ~(|state) | _io_sndmsg_T_1;	// abp.scala:127:7, :136:22, :150:{23,48,57}
  assign io_state = state;	// abp.scala:127:7, :136:22
endmodule

module receiver(	// abp.scala:292:7
  input        clock,	// abp.scala:292:7
               reset,	// abp.scala:292:7
  input  [2:0] io_message,	// abp.scala:293:14
  input        io_active,	// abp.scala:293:14
  output [1:0] io_ack,	// abp.scala:293:14
  output       io_rcvmsg,	// abp.scala:293:14
  output [2:0] io_state	// abp.scala:293:14
);

  reg  [1:0]  ackReg;	// abp.scala:301:23
  reg  [2:0]  state;	// abp.scala:302:22
  reg         exit2;	// abp.scala:303:22
  reg  [15:0] lfsr;	// abp.scala:307:21
  wire        _io_rcvmsg_T = state == 3'h2;	// abp.scala:302:22, :312:23
  wire        _io_rcvmsg_T_1 = state == 3'h5;	// abp.scala:302:22, :312:58
  wire        _GEN = state == 3'h0;	// abp.scala:302:22, :317:18
  wire        _GEN_0 = state == 3'h1;	// abp.scala:302:22, :317:54
  wire        _GEN_1 = state == 3'h3;	// abp.scala:302:22, :318:46
  wire        _GEN_2 = state == 3'h4;	// abp.scala:302:22, :319:11
  reg         hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire        hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// abp.scala:292:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  Receiver_state_should_be_valid:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     _GEN | _GEN_0 | _io_rcvmsg_T | _GEN_1 | _GEN_2 | _io_rcvmsg_T_1);	// abp.scala:312:{23,58}, :317:{18,54}, :318:46, :319:{11,38}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire        _GEN_3 = ackReg == 2'h2;	// abp.scala:301:23, :323:86
  ACK0_state_should_have_AM0_or_AERR:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_io_rcvmsg_T & ~(ackReg == 2'h0 | _GEN_3)));	// abp.scala:301:23, :312:23, :323:{12,46,49,58,76,86}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  ACK1_state_should_have_AM1_or_AERR:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_io_rcvmsg_T_1 & ~(ackReg == 2'h1 | _GEN_3)));	// abp.scala:301:23, :312:58, :323:86, :326:{12,46,49,58,76}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire        _GEN_4 = io_message == 3'h2 | io_message == 3'h0;	// abp.scala:302:22, :312:23, :331:{18,40,54}
  WAIT0_should_only_exit_for_DATA10_or_DATA00:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_GEN_0 & exit2 & ~_GEN_4));	// abp.scala:303:22, :317:54, :330:{12,58}, :331:{5,40}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire        _GEN_5 = io_message == 3'h3 | io_message == 3'h1;	// abp.scala:317:54, :318:46, :335:{18,40,54}
  WAIT1_should_only_exit_for_DATA11_or_DATA01:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_GEN_2 & exit2 & ~_GEN_5));	// abp.scala:303:22, :319:11, :334:{12,58}, :335:{5,40}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire [2:0]  nextState = _io_rcvmsg_T ? 3'h3 : _io_rcvmsg_T_1 ? 3'h0 : state;	// abp.scala:302:22, :312:{23,58}, :318:46, :415:15, :417:50, :418:17, :419:56, :420:17
  ACK0_should_transition_to_INIT1:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_io_rcvmsg_T & nextState != 3'h3));	// abp.scala:312:23, :318:46, :339:{12,46,68}, :417:50, :418:17, :419:56, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  ACK1_should_transition_to_INIT0:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_io_rcvmsg_T_1 & (|nextState)));	// abp.scala:312:58, :342:{12,46,68}, :417:50, :418:17, :419:56, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// abp.scala:292:7
    if (reset) begin	// abp.scala:292:7
      hasBeenResetReg <= 1'h1;	// abp.scala:292:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
      ackReg <= 2'h2;	// abp.scala:301:23
      state <= 3'h0;	// abp.scala:302:22
      exit2 <= 1'h0;	// abp.scala:292:7, :303:22
      lfsr <= 16'h1;	// abp.scala:307:21
    end
    else begin	// abp.scala:292:7
      if (io_active) begin	// abp.scala:293:14
        automatic logic [1:0]      _GEN_6;	// abp.scala:360:25, :361:22, :363:22
        automatic logic [1:0]      _GEN_7;	// abp.scala:371:21, :372:18, :374:18
        automatic logic [7:0][1:0] _GEN_8;	// abp.scala:301:23, :317:{18,54}, :318:46, :319:11, :346:19, :352:22, :371:21, :383:22, :402:21
        automatic logic [7:0][2:0] _GEN_9;	// abp.scala:302:22, :317:{18,54}, :318:46, :319:11, :346:19, :349:15, :352:22, :376:15, :380:15, :383:22, :407:15
        _GEN_6 = lfsr[0] ? 2'h1 : 2'h2;	// abp.scala:301:23, :307:21, :309:19, :326:58, :360:25, :361:22, :363:22
        _GEN_7 = {~(lfsr[0]), 1'h0};	// abp.scala:292:7, :307:21, :309:19, :371:21, :372:18, :374:18
        _GEN_8 =
          {{ackReg},
           {ackReg},
           {_GEN_6},
           {exit2 | _GEN_5 ? ackReg : _GEN_7},
           {ackReg},
           {_GEN_7},
           {exit2 | _GEN_4 ? ackReg : _GEN_6},
           {ackReg}};	// abp.scala:301:23, :303:22, :317:{18,54}, :318:46, :319:11, :331:40, :335:40, :346:19, :352:22, :353:50, :360:25, :361:22, :363:22, :371:21, :372:18, :374:18, :383:22, :384:50, :402:21
        ackReg <= _GEN_8[state];	// abp.scala:301:23, :302:22, :317:{18,54}, :318:46, :319:11, :346:19, :352:22, :371:21, :383:22, :402:21
        _GEN_9 =
          {{state},
           {state},
           {3'h0},
           {exit2 ? 3'h5 : state},
           {3'h4},
           {3'h3},
           {exit2 ? 3'h2 : state},
           {3'h1}};	// abp.scala:302:22, :303:22, :312:{23,58}, :317:{18,54}, :318:46, :319:11, :346:19, :349:15, :352:22, :367:17, :376:15, :380:15, :383:22, :398:17, :407:15
        state <= _GEN_9[state];	// abp.scala:302:22, :317:{18,54}, :318:46, :319:11, :346:19, :349:15, :352:22, :376:15, :380:15, :383:22, :407:15
        exit2 <=
          ~_GEN
          & (_GEN_0
               ? ~exit2 & _GEN_4 | exit2
               : state == 3'h2 ? exit2 : ~_GEN_1 & (_GEN_2 & ~exit2 & _GEN_5 | exit2));	// abp.scala:302:22, :303:22, :312:23, :317:{18,54}, :318:46, :319:11, :331:40, :335:40, :346:19, :348:15, :352:{14,22}, :353:50, :354:19, :356:56, :357:19, :379:15, :383:22, :384:50, :385:19, :387:56, :388:19
      end
      lfsr <= {lfsr[14:0], lfsr[15] ^ lfsr[13] ^ lfsr[12] ^ lfsr[10]};	// abp.scala:307:21, :308:{14,19,31,42,53,58,64}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// abp.scala:292:7
    `ifdef FIRRTL_BEFORE_INITIAL	// abp.scala:292:7
      `FIRRTL_BEFORE_INITIAL	// abp.scala:292:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// abp.scala:292:7
      automatic logic [31:0] _RANDOM[0:0];	// abp.scala:292:7
      `ifdef INIT_RANDOM_PROLOG_	// abp.scala:292:7
        `INIT_RANDOM_PROLOG_	// abp.scala:292:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// abp.scala:292:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// abp.scala:292:7
        ackReg = _RANDOM[/*Zero width*/ 1'b0][1:0];	// abp.scala:292:7, :301:23
        state = _RANDOM[/*Zero width*/ 1'b0][4:2];	// abp.scala:292:7, :301:23, :302:22
        exit2 = _RANDOM[/*Zero width*/ 1'b0][5];	// abp.scala:292:7, :301:23, :303:22
        lfsr = _RANDOM[/*Zero width*/ 1'b0][23:8];	// abp.scala:292:7, :301:23, :307:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// abp.scala:292:7
      `FIRRTL_AFTER_INITIAL	// abp.scala:292:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  assign io_ack = ackReg;	// abp.scala:292:7, :301:23
  assign io_rcvmsg = _io_rcvmsg_T | _io_rcvmsg_T_1;	// abp.scala:292:7, :312:{23,49,58}
  assign io_state = state;	// abp.scala:292:7, :302:22
endmodule

module arbiter(	// abp.scala:427:7
  input  clock,	// abp.scala:427:7
         reset,	// abp.scala:427:7
  output io_o1,	// abp.scala:428:14
         io_o2	// abp.scala:428:14
);

  reg         o1Reg;	// abp.scala:433:22
  reg         o2Reg;	// abp.scala:434:22
  reg  [15:0] lfsr;	// abp.scala:437:21
  reg         hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire        hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// abp.scala:427:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  Arbiter3A_o1_and_o2_should_never_both_be_true:
    assert property (@(posedge clock) disable iff (~hasBeenReset) ~(o1Reg & o2Reg));	// abp.scala:433:22, :434:22, :446:{12,20}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Arbiter3A_at_least_one_output_should_be_active:
    assert property (@(posedge clock) disable iff (~hasBeenReset) o1Reg | o2Reg);	// abp.scala:433:22, :434:22, :449:18, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Arbiter3A_exactly_one_output_should_be_active:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     {1'h0, o2Reg} + {1'h0, o1Reg} == 2'h1);	// abp.scala:427:7, :433:22, :434:22, :452:15, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// abp.scala:427:7
    if (reset) begin	// abp.scala:427:7
      hasBeenResetReg <= 1'h1;	// abp.scala:427:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
      o1Reg <= 1'h0;	// abp.scala:427:7, :433:22
      o2Reg <= 1'h0;	// abp.scala:427:7, :434:22
      lfsr <= 16'h1;	// abp.scala:437:21
    end
    else begin	// abp.scala:427:7
      o1Reg <= ~(lfsr[0]);	// abp.scala:433:22, :437:21, :439:15, :452:15, :454:11, :455:11, :458:11
      o2Reg <= lfsr[0];	// abp.scala:434:22, :437:21, :439:15
      lfsr <= {lfsr[14:0], lfsr[15] ^ lfsr[13] ^ lfsr[12] ^ lfsr[10]};	// abp.scala:437:21, :438:{14,19,31,42,53,58,64}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// abp.scala:427:7
    `ifdef FIRRTL_BEFORE_INITIAL	// abp.scala:427:7
      `FIRRTL_BEFORE_INITIAL	// abp.scala:427:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// abp.scala:427:7
      automatic logic [31:0] _RANDOM[0:0];	// abp.scala:427:7
      `ifdef INIT_RANDOM_PROLOG_	// abp.scala:427:7
        `INIT_RANDOM_PROLOG_	// abp.scala:427:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// abp.scala:427:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// abp.scala:427:7
        o1Reg = _RANDOM[/*Zero width*/ 1'b0][0];	// abp.scala:427:7, :433:22
        o2Reg = _RANDOM[/*Zero width*/ 1'b0][1];	// abp.scala:427:7, :433:22, :434:22
        lfsr = _RANDOM[/*Zero width*/ 1'b0][17:2];	// abp.scala:427:7, :433:22, :437:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// abp.scala:427:7
      `FIRRTL_AFTER_INITIAL	// abp.scala:427:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  assign io_o1 = o1Reg;	// abp.scala:427:7, :433:22
  assign io_o2 = o2Reg;	// abp.scala:427:7, :434:22
endmodule

module abp(	// abp.scala:46:7
  input        clock,	// abp.scala:46:7
               reset,	// abp.scala:46:7
  output [2:0] io_message,	// abp.scala:47:14
  output [1:0] io_ack,	// abp.scala:47:14
  output       io_o1,	// abp.scala:47:14
               io_o2,	// abp.scala:47:14
               io_sndmsg,	// abp.scala:47:14
               io_rcvmsg	// abp.scala:47:14
);

  wire        _a_io_o1;	// abp.scala:66:17
  wire        _a_io_o2;	// abp.scala:66:17
  wire [1:0]  _r_io_ack;	// abp.scala:65:17
  wire        _r_io_rcvmsg;	// abp.scala:65:17
  wire [2:0]  _r_io_state;	// abp.scala:65:17
  wire [2:0]  _s_io_message;	// abp.scala:64:17
  wire        _s_io_sndmsg;	// abp.scala:64:17
  wire [2:0]  _s_io_state;	// abp.scala:64:17
  wire        _resetCounter_notChaos;	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
  reg         hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire        hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// abp.scala:123:22, src/main/scala/chisel3/ltl/LTL.scala:362:39
  Arbiter_mutual_exclusion_violated:
    assert property (@(posedge clock) disable iff (~hasBeenReset) ~(_a_io_o1 & _a_io_o2));	// abp.scala:66:17, :94:{12,21}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire        _GEN = _s_io_sndmsg & _a_io_o1;	// abp.scala:64:17, :66:17, :97:33
  Sender_message_should_be_acknowledged_by_receiver:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN |-> ##[1:100]
                     _r_io_rcvmsg & _a_io_o2);	// abp.scala:65:17, :66:17, :97:{33,55}, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  wire        _GEN_0 = _s_io_message == 3'h2;	// abp.scala:64:17, :101:18
  wire        _GEN_1 = _s_io_message == 3'h0;	// abp.scala:46:7, :64:17, :101:55
  wire        _GEN_2 = _r_io_ack == 2'h2;	// abp.scala:46:7, :65:17, :102:44
  Receiver_should_send_AM0_or_AERR_when_expecting_DATA102FDATA00:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_a_io_o2 & _r_io_state == 3'h1 & (_GEN_0 | _GEN_1)
                       & ~(_r_io_ack == 2'h0 | _GEN_2)));	// abp.scala:46:7, :65:17, :66:17, :100:{12,35}, :101:{18,40,55,78}, :102:{5,15,33,44}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire        _GEN_3 = _s_io_message == 3'h3;	// abp.scala:64:17, :106:18
  wire        _GEN_4 = _s_io_message == 3'h1;	// abp.scala:46:7, :64:17, :106:55
  Receiver_should_send_AM1_or_AERR_when_expecting_DATA112FDATA01:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_a_io_o2 & _r_io_state == 3'h4 & (_GEN_3 | _GEN_4)
                       & ~(_r_io_ack == 2'h1 | _GEN_2)));	// abp.scala:46:7, :65:17, :66:17, :102:44, :105:{12,35}, :106:{18,40,55,78}, :107:{5,15,33}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Sender_should_not_send_messages_in_WAIT_states:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_a_io_o1 & (_s_io_state == 3'h2 | _s_io_state == 3'h5)
                       & _s_io_sndmsg));	// abp.scala:64:17, :66:17, :101:18, :111:{12,36,61,75,101}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Message_should_be_valid_when_sent:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_GEN
                       & ~(_GEN_1 | _GEN_4 | _GEN_0 | _GEN_3 | _s_io_message == 3'h4)));	// abp.scala:46:7, :64:17, :97:33, :101:{18,55}, :106:{18,55}, :115:{12,35,38}, :118:39, :119:17, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg  [63:0] timer;	// abp.scala:123:22
  reg  [63:0] timer_1;	// abp.scala:124:22
  `ifndef SYNTHESIS	// abp.scala:123:22
    always @(posedge clock) begin	// abp.scala:123:22
      automatic logic _GEN_5 = _resetCounter_notChaos & ~reset;	// abp.scala:123:22, home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
      if (_GEN_5 & timer > 64'h32) begin	// abp.scala:123:22
        if (`ASSERT_VERBOSE_COND_)	// abp.scala:123:22
          $error("Assertion failed: o1 should be activated within 50 cycles\n    at Formal.scala:113 assert(timer <= n.U, msg)\n");	// abp.scala:123:22
        if (`STOP_COND_)	// abp.scala:123:22
          $fatal;	// abp.scala:123:22
      end
      if (_GEN_5 & timer_1 > 64'h32) begin	// abp.scala:123:22, :124:22
        if (`ASSERT_VERBOSE_COND_)	// abp.scala:124:22
          $error("Assertion failed: o2 should be activated within 50 cycles\n    at Formal.scala:113 assert(timer <= n.U, msg)\n");	// abp.scala:124:22
        if (`STOP_COND_)	// abp.scala:124:22
          $fatal;	// abp.scala:124:22
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// abp.scala:46:7
    if (reset) begin	// abp.scala:46:7
      hasBeenResetReg <= 1'h1;	// abp.scala:123:22, src/main/scala/chisel3/ltl/LTL.scala:362:39
      timer <= 64'h0;	// abp.scala:123:22
      timer_1 <= 64'h0;	// abp.scala:123:22, :124:22
    end
    else begin	// abp.scala:46:7
      if (_a_io_o1) begin	// abp.scala:66:17
      end
      else	// abp.scala:66:17
        timer <= timer + 64'h1;	// abp.scala:123:22
      if (_a_io_o2) begin	// abp.scala:66:17
      end
      else	// abp.scala:66:17
        timer_1 <= timer_1 + 64'h1;	// abp.scala:123:22, :124:22
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// abp.scala:46:7
    `ifdef FIRRTL_BEFORE_INITIAL	// abp.scala:46:7
      `FIRRTL_BEFORE_INITIAL	// abp.scala:46:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// abp.scala:46:7
      automatic logic [31:0] _RANDOM[0:3];	// abp.scala:46:7
      `ifdef INIT_RANDOM_PROLOG_	// abp.scala:46:7
        `INIT_RANDOM_PROLOG_	// abp.scala:46:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// abp.scala:46:7
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// abp.scala:46:7
        end	// abp.scala:46:7
        timer = {_RANDOM[2'h0], _RANDOM[2'h1]};	// abp.scala:46:7, :123:22
        timer_1 = {_RANDOM[2'h2], _RANDOM[2'h3]};	// abp.scala:46:7, :124:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// abp.scala:46:7
      `FIRRTL_AFTER_INITIAL	// abp.scala:46:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (_resetCounter_notChaos)
  );
  sender s (	// abp.scala:64:17
    .clock      (clock),
    .reset      (reset),
    .io_ack     (_r_io_ack),	// abp.scala:65:17
    .io_active  (_a_io_o1),	// abp.scala:66:17
    .io_message (_s_io_message),
    .io_sndmsg  (_s_io_sndmsg),
    .io_state   (_s_io_state)
  );
  receiver r (	// abp.scala:65:17
    .clock      (clock),
    .reset      (reset),
    .io_message (_s_io_message),	// abp.scala:64:17
    .io_active  (_a_io_o2),	// abp.scala:66:17
    .io_ack     (_r_io_ack),
    .io_rcvmsg  (_r_io_rcvmsg),
    .io_state   (_r_io_state)
  );
  arbiter a (	// abp.scala:66:17
    .clock (clock),
    .reset (reset),
    .io_o1 (_a_io_o1),
    .io_o2 (_a_io_o2)
  );
  assign io_message = _s_io_message;	// abp.scala:46:7, :64:17
  assign io_ack = _r_io_ack;	// abp.scala:46:7, :65:17
  assign io_o1 = _a_io_o1;	// abp.scala:46:7, :66:17
  assign io_o2 = _a_io_o2;	// abp.scala:46:7, :66:17
  assign io_sndmsg = _s_io_sndmsg;	// abp.scala:46:7, :64:17
  assign io_rcvmsg = _r_io_rcvmsg;	// abp.scala:46:7, :65:17
endmodule


// ----- 8< ----- FILE "./ResetCounter.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.1

module ResetCounter(
    input clk,
    input reset,
    output [31:0] timeSinceReset,
    output notChaos
);

reg [31:0] count;
reg flag;
initial begin
  count = 0;
  flag = 0;
end

assign timeSinceReset = count;
assign notChaos = flag;

always @(posedge clk) begin
    if (reset) begin
        count <= 0;
        flag <= 1;
    end else if (flag) begin
        count <= count + 1;
    end
end

endmodule
    

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----
