// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// external module ResetCounter

module swap(	// swap.scala:6:7
  input        clock,	// swap.scala:6:7
               reset,	// swap.scala:6:7
  input  [2:0] io_i,	// swap.scala:7:14
  output [2:0] io_x_out_0,	// swap.scala:7:14
               io_x_out_1,	// swap.scala:7:14
               io_x_out_2,	// swap.scala:7:14
               io_x_out_3,	// swap.scala:7:14
               io_x_out_4,	// swap.scala:7:14
               io_x_out_5,	// swap.scala:7:14
               io_x_out_6,	// swap.scala:7:14
               io_x_out_7,	// swap.scala:7:14
               io_tmp_out,	// swap.scala:7:14
               io_p_out,	// swap.scala:7:14
               io_m_out	// swap.scala:7:14
);

  wire [31:0]     _resetCounter_timeSinceReset;	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
  wire            _resetCounter_notChaos;	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
  reg  [2:0]      x_0;	// swap.scala:17:18
  reg  [2:0]      x_1;	// swap.scala:17:18
  reg  [2:0]      x_2;	// swap.scala:17:18
  reg  [2:0]      x_3;	// swap.scala:17:18
  reg  [2:0]      x_4;	// swap.scala:17:18
  reg  [2:0]      x_5;	// swap.scala:17:18
  reg  [2:0]      x_6;	// swap.scala:17:18
  reg  [2:0]      x_7;	// swap.scala:17:18
  reg  [2:0]      tmp;	// swap.scala:20:20
  wire [2:0]      p = (&io_i) ? 3'h7 : io_i;	// swap.scala:17:26, :27:{11,17}
  wire [2:0]      _m_T_1 = p - 3'h1;	// swap.scala:27:11, :28:33
  wire [2:0]      m = (|p) ? _m_T_1 : 3'h7;	// swap.scala:17:26, :27:11, :28:{11,14,33}
  wire [7:0][2:0] _GEN = {{x_7}, {x_6}, {x_5}, {x_4}, {x_3}, {x_2}, {x_1}, {x_0}};	// swap.scala:17:18, :36:9
  reg             hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire            hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// src/main/scala/chisel3/ltl/LTL.scala:362:39, swap.scala:28:33
  p_should_not_exceed_Nm1:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:28:33
  m_should_not_exceed_Nm1:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:28:33
  m_should_be_Nm1_when_p_is_0:
    assert property (@(posedge clock) disable iff (~hasBeenReset) (|p) | (&m));	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:27:11, :28:{11,14}, :38:10, :56:22
  m_should_be_p2D1_when_p_3E_0:
    assert property (@(posedge clock) disable iff (~hasBeenReset) ~(|p) | m == _m_T_1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:27:11, :28:{11,14,33}, :59:{22,27}
  x5Bp5D_should_equal_previous_x5Bm5D_after_swap:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN[p] == _GEN[m]);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:27:11, :28:11, :36:9, :37:10, :70:17
  x5Bm5D_should_equal_previous_x5Bp5D_after_swap:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN[m] == _GEN[p]);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:27:11, :28:11, :36:9, :37:10, :71:17
  x5B05D_should_remain_unchanged_when_not_involved_in_swap:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:28:33
  x5B15D_should_remain_unchanged_when_not_involved_in_swap:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:28:33
  x5B25D_should_remain_unchanged_when_not_involved_in_swap:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:28:33
  x5B35D_should_remain_unchanged_when_not_involved_in_swap:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:28:33
  x5B45D_should_remain_unchanged_when_not_involved_in_swap:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:28:33
  x5B55D_should_remain_unchanged_when_not_involved_in_swap:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:28:33
  x5B65D_should_remain_unchanged_when_not_involved_in_swap:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:28:33
  x5B75D_should_remain_unchanged_when_not_involved_in_swap:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:28:33
  tmp_should_hold_previous_x5Bp5D_value:
    assert property (@(posedge clock) disable iff (~hasBeenReset) tmp == _GEN[p]);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:20:20, :27:11, :36:9, :81:16
  `ifndef SYNTHESIS	// swap.scala:85:13
    always @(posedge clock) begin	// swap.scala:85:13
      automatic logic _GEN_0 =
        _resetCounter_notChaos & _resetCounter_timeSinceReset == 32'h0 & ~reset;	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36, swap.scala:85:13
      if (_GEN_0 & (|x_0)) begin	// swap.scala:17:18, :85:{13,24}
        if (`ASSERT_VERBOSE_COND_)	// swap.scala:85:13
          $error("Assertion failed: Initial value of x[0] should be 0\n    at Formal.scala:29 assert(cond, msg)\n");	// swap.scala:85:13
        if (`STOP_COND_)	// swap.scala:85:13
          $fatal;	// swap.scala:85:13
      end
      if (_GEN_0 & x_1 != 3'h1) begin	// swap.scala:6:7, :17:18, :85:{13,24}
        if (`ASSERT_VERBOSE_COND_)	// swap.scala:85:13
          $error("Assertion failed: Initial value of x[1] should be 1\n    at Formal.scala:29 assert(cond, msg)\n");	// swap.scala:85:13
        if (`STOP_COND_)	// swap.scala:85:13
          $fatal;	// swap.scala:85:13
      end
      if (_GEN_0 & x_2 != 3'h2) begin	// swap.scala:17:{18,26}, :85:{13,24}
        if (`ASSERT_VERBOSE_COND_)	// swap.scala:85:13
          $error("Assertion failed: Initial value of x[2] should be 2\n    at Formal.scala:29 assert(cond, msg)\n");	// swap.scala:85:13
        if (`STOP_COND_)	// swap.scala:85:13
          $fatal;	// swap.scala:85:13
      end
      if (_GEN_0 & x_3 != 3'h3) begin	// swap.scala:17:{18,26}, :85:{13,24}
        if (`ASSERT_VERBOSE_COND_)	// swap.scala:85:13
          $error("Assertion failed: Initial value of x[3] should be 3\n    at Formal.scala:29 assert(cond, msg)\n");	// swap.scala:85:13
        if (`STOP_COND_)	// swap.scala:85:13
          $fatal;	// swap.scala:85:13
      end
      if (_GEN_0 & x_4 != 3'h4) begin	// swap.scala:6:7, :17:18, :85:{13,24}
        if (`ASSERT_VERBOSE_COND_)	// swap.scala:85:13
          $error("Assertion failed: Initial value of x[4] should be 4\n    at Formal.scala:29 assert(cond, msg)\n");	// swap.scala:85:13
        if (`STOP_COND_)	// swap.scala:85:13
          $fatal;	// swap.scala:85:13
      end
      if (_GEN_0 & x_5 != 3'h5) begin	// swap.scala:17:{18,26}, :85:{13,24}
        if (`ASSERT_VERBOSE_COND_)	// swap.scala:85:13
          $error("Assertion failed: Initial value of x[5] should be 5\n    at Formal.scala:29 assert(cond, msg)\n");	// swap.scala:85:13
        if (`STOP_COND_)	// swap.scala:85:13
          $fatal;	// swap.scala:85:13
      end
      if (_GEN_0 & x_6 != 3'h6) begin	// swap.scala:17:{18,26}, :85:{13,24}
        if (`ASSERT_VERBOSE_COND_)	// swap.scala:85:13
          $error("Assertion failed: Initial value of x[6] should be 6\n    at Formal.scala:29 assert(cond, msg)\n");	// swap.scala:85:13
        if (`STOP_COND_)	// swap.scala:85:13
          $fatal;	// swap.scala:85:13
      end
      if (_GEN_0 & x_7 != 3'h7) begin	// swap.scala:17:{18,26}, :85:{13,24}
        if (`ASSERT_VERBOSE_COND_)	// swap.scala:85:13
          $error("Assertion failed: Initial value of x[7] should be 7\n    at Formal.scala:29 assert(cond, msg)\n");	// swap.scala:85:13
        if (`STOP_COND_)	// swap.scala:85:13
          $fatal;	// swap.scala:85:13
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  x5B05D_and_x5B15D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_0 != x_1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B05D_and_x5B25D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_0 != x_2);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B05D_and_x5B35D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_0 != x_3);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B05D_and_x5B45D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_0 != x_4);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B05D_and_x5B55D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_0 != x_5);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B05D_and_x5B65D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_0 != x_6);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B05D_and_x5B75D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_0 != x_7);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B15D_and_x5B25D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_1 != x_2);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B15D_and_x5B35D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_1 != x_3);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B15D_and_x5B45D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_1 != x_4);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B15D_and_x5B55D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_1 != x_5);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B15D_and_x5B65D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_1 != x_6);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B15D_and_x5B75D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_1 != x_7);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B25D_and_x5B35D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_2 != x_3);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B25D_and_x5B45D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_2 != x_4);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B25D_and_x5B55D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_2 != x_5);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B25D_and_x5B65D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_2 != x_6);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B25D_and_x5B75D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_2 != x_7);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B35D_and_x5B45D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_3 != x_4);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B35D_and_x5B55D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_3 != x_5);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B35D_and_x5B65D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_3 != x_6);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B35D_and_x5B75D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_3 != x_7);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B45D_and_x5B55D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_4 != x_5);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B45D_and_x5B65D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_4 != x_6);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B45D_and_x5B75D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_4 != x_7);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B55D_and_x5B65D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_5 != x_6);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B55D_and_x5B75D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_5 != x_7);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  x5B65D_and_x5B75D_should_have_different_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset) x_6 != x_7);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:17:18, :92:22
  reg  [2:0]      x_two_cycles_ago_REG_0;	// swap.scala:98:41
  reg  [2:0]      x_two_cycles_ago_REG_1;	// swap.scala:98:41
  reg  [2:0]      x_two_cycles_ago_REG_2;	// swap.scala:98:41
  reg  [2:0]      x_two_cycles_ago_REG_3;	// swap.scala:98:41
  reg  [2:0]      x_two_cycles_ago_REG_4;	// swap.scala:98:41
  reg  [2:0]      x_two_cycles_ago_REG_5;	// swap.scala:98:41
  reg  [2:0]      x_two_cycles_ago_REG_6;	// swap.scala:98:41
  reg  [2:0]      x_two_cycles_ago_REG_7;	// swap.scala:98:41
  reg  [2:0]      x_two_cycles_ago_0;	// swap.scala:98:33
  reg  [2:0]      x_two_cycles_ago_1;	// swap.scala:98:33
  reg  [2:0]      x_two_cycles_ago_2;	// swap.scala:98:33
  reg  [2:0]      x_two_cycles_ago_3;	// swap.scala:98:33
  reg  [2:0]      x_two_cycles_ago_4;	// swap.scala:98:33
  reg  [2:0]      x_two_cycles_ago_5;	// swap.scala:98:33
  reg  [2:0]      x_two_cycles_ago_6;	// swap.scala:98:33
  reg  [2:0]      x_two_cycles_ago_7;	// swap.scala:98:33
  reg  [2:0]      p_two_cycles_ago_REG;	// swap.scala:99:41
  reg  [2:0]      p_two_cycles_ago;	// swap.scala:99:33
  reg  [2:0]      m_two_cycles_ago_REG;	// swap.scala:100:41
  reg  [2:0]      m_two_cycles_ago;	// swap.scala:100:33
  wire [7:0][2:0] _GEN_1 =
    {{x_two_cycles_ago_7},
     {x_two_cycles_ago_6},
     {x_two_cycles_ago_5},
     {x_two_cycles_ago_4},
     {x_two_cycles_ago_3},
     {x_two_cycles_ago_2},
     {x_two_cycles_ago_1},
     {x_two_cycles_ago_0}};	// swap.scala:98:33, :104:18
  Swapping_same_indices_twice_should_return_to_original_values:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     p != p_two_cycles_ago | m != m_two_cycles_ago | _GEN[p] == _GEN_1[p]
                     & _GEN[m] == _GEN_1[m]);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, swap.scala:27:11, :28:11, :36:9, :37:10, :99:33, :100:33, :103:{15,41,63}, :104:{18,42,50}
  always @(posedge clock) begin	// swap.scala:6:7
    if (reset) begin	// swap.scala:6:7
      hasBeenResetReg <= 1'h1;	// src/main/scala/chisel3/ltl/LTL.scala:362:39, swap.scala:28:33
      x_0 <= 3'h0;	// swap.scala:6:7, :17:18
      x_1 <= 3'h1;	// swap.scala:6:7, :17:18
      x_2 <= 3'h2;	// swap.scala:17:{18,26}
      x_3 <= 3'h3;	// swap.scala:17:{18,26}
      x_4 <= 3'h4;	// swap.scala:6:7, :17:18
      x_5 <= 3'h5;	// swap.scala:17:{18,26}
      x_6 <= 3'h6;	// swap.scala:17:{18,26}
      x_7 <= 3'h7;	// swap.scala:17:{18,26}
      tmp <= 3'h0;	// swap.scala:6:7, :20:20
    end
    else begin	// swap.scala:6:7
      if (m == 3'h0)	// swap.scala:6:7, :28:11, :38:10
        x_0 <= tmp;	// swap.scala:17:18, :20:20
      else if (~(|p))	// swap.scala:27:11, :28:14
        x_0 <= _GEN[m];	// swap.scala:17:18, :28:11, :36:9, :37:10
      if (m == 3'h1)	// swap.scala:6:7, :28:11, :38:10
        x_1 <= tmp;	// swap.scala:17:18, :20:20
      else if (p == 3'h1)	// swap.scala:6:7, :27:11, :37:10
        x_1 <= _GEN[m];	// swap.scala:17:18, :28:11, :36:9, :37:10
      if (m == 3'h2)	// swap.scala:17:26, :28:11, :38:10
        x_2 <= tmp;	// swap.scala:17:18, :20:20
      else if (p == 3'h2)	// swap.scala:17:26, :27:11, :37:10
        x_2 <= _GEN[m];	// swap.scala:17:18, :28:11, :36:9, :37:10
      if (m == 3'h3)	// swap.scala:17:26, :28:11, :38:10
        x_3 <= tmp;	// swap.scala:17:18, :20:20
      else if (p == 3'h3)	// swap.scala:17:26, :27:11, :37:10
        x_3 <= _GEN[m];	// swap.scala:17:18, :28:11, :36:9, :37:10
      if (m == 3'h4)	// swap.scala:6:7, :28:11, :38:10
        x_4 <= tmp;	// swap.scala:17:18, :20:20
      else if (p == 3'h4)	// swap.scala:6:7, :27:11, :37:10
        x_4 <= _GEN[m];	// swap.scala:17:18, :28:11, :36:9, :37:10
      if (m == 3'h5)	// swap.scala:17:26, :28:11, :38:10
        x_5 <= tmp;	// swap.scala:17:18, :20:20
      else if (p == 3'h5)	// swap.scala:17:26, :27:11, :37:10
        x_5 <= _GEN[m];	// swap.scala:17:18, :28:11, :36:9, :37:10
      if (m == 3'h6)	// swap.scala:17:26, :28:11, :38:10
        x_6 <= tmp;	// swap.scala:17:18, :20:20
      else if (p == 3'h6)	// swap.scala:17:26, :27:11, :37:10
        x_6 <= _GEN[m];	// swap.scala:17:18, :28:11, :36:9, :37:10
      if (&m)	// swap.scala:28:11, :38:10
        x_7 <= tmp;	// swap.scala:17:18, :20:20
      else if (&p)	// swap.scala:27:11, :37:10
        x_7 <= _GEN[m];	// swap.scala:17:18, :28:11, :36:9, :37:10
      tmp <= _GEN[p];	// swap.scala:20:20, :27:11, :36:9
    end
    x_two_cycles_ago_REG_0 <= x_0;	// swap.scala:17:18, :98:41
    x_two_cycles_ago_REG_1 <= x_1;	// swap.scala:17:18, :98:41
    x_two_cycles_ago_REG_2 <= x_2;	// swap.scala:17:18, :98:41
    x_two_cycles_ago_REG_3 <= x_3;	// swap.scala:17:18, :98:41
    x_two_cycles_ago_REG_4 <= x_4;	// swap.scala:17:18, :98:41
    x_two_cycles_ago_REG_5 <= x_5;	// swap.scala:17:18, :98:41
    x_two_cycles_ago_REG_6 <= x_6;	// swap.scala:17:18, :98:41
    x_two_cycles_ago_REG_7 <= x_7;	// swap.scala:17:18, :98:41
    x_two_cycles_ago_0 <= x_two_cycles_ago_REG_0;	// swap.scala:98:{33,41}
    x_two_cycles_ago_1 <= x_two_cycles_ago_REG_1;	// swap.scala:98:{33,41}
    x_two_cycles_ago_2 <= x_two_cycles_ago_REG_2;	// swap.scala:98:{33,41}
    x_two_cycles_ago_3 <= x_two_cycles_ago_REG_3;	// swap.scala:98:{33,41}
    x_two_cycles_ago_4 <= x_two_cycles_ago_REG_4;	// swap.scala:98:{33,41}
    x_two_cycles_ago_5 <= x_two_cycles_ago_REG_5;	// swap.scala:98:{33,41}
    x_two_cycles_ago_6 <= x_two_cycles_ago_REG_6;	// swap.scala:98:{33,41}
    x_two_cycles_ago_7 <= x_two_cycles_ago_REG_7;	// swap.scala:98:{33,41}
    p_two_cycles_ago_REG <= p;	// swap.scala:27:11, :99:41
    p_two_cycles_ago <= p_two_cycles_ago_REG;	// swap.scala:99:{33,41}
    m_two_cycles_ago_REG <= m;	// swap.scala:28:11, :100:41
    m_two_cycles_ago <= m_two_cycles_ago_REG;	// swap.scala:100:{33,41}
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// swap.scala:6:7
    `ifdef FIRRTL_BEFORE_INITIAL	// swap.scala:6:7
      `FIRRTL_BEFORE_INITIAL	// swap.scala:6:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// swap.scala:6:7
      automatic logic [31:0] _RANDOM[0:3];	// swap.scala:6:7
      `ifdef INIT_RANDOM_PROLOG_	// swap.scala:6:7
        `INIT_RANDOM_PROLOG_	// swap.scala:6:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// swap.scala:6:7
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// swap.scala:6:7
        end	// swap.scala:6:7
        x_0 = _RANDOM[2'h0][2:0];	// swap.scala:6:7, :17:18
        x_1 = _RANDOM[2'h0][5:3];	// swap.scala:6:7, :17:18
        x_2 = _RANDOM[2'h0][8:6];	// swap.scala:6:7, :17:18
        x_3 = _RANDOM[2'h0][11:9];	// swap.scala:6:7, :17:18
        x_4 = _RANDOM[2'h0][14:12];	// swap.scala:6:7, :17:18
        x_5 = _RANDOM[2'h0][17:15];	// swap.scala:6:7, :17:18
        x_6 = _RANDOM[2'h0][20:18];	// swap.scala:6:7, :17:18
        x_7 = _RANDOM[2'h0][23:21];	// swap.scala:6:7, :17:18
        tmp = _RANDOM[2'h0][26:24];	// swap.scala:6:7, :17:18, :20:20
        x_two_cycles_ago_REG_0 = _RANDOM[2'h1][30:28];	// swap.scala:6:7, :98:41
        x_two_cycles_ago_REG_1 = {_RANDOM[2'h1][31], _RANDOM[2'h2][1:0]};	// swap.scala:6:7, :98:41
        x_two_cycles_ago_REG_2 = _RANDOM[2'h2][4:2];	// swap.scala:6:7, :98:41
        x_two_cycles_ago_REG_3 = _RANDOM[2'h2][7:5];	// swap.scala:6:7, :98:41
        x_two_cycles_ago_REG_4 = _RANDOM[2'h2][10:8];	// swap.scala:6:7, :98:41
        x_two_cycles_ago_REG_5 = _RANDOM[2'h2][13:11];	// swap.scala:6:7, :98:41
        x_two_cycles_ago_REG_6 = _RANDOM[2'h2][16:14];	// swap.scala:6:7, :98:41
        x_two_cycles_ago_REG_7 = _RANDOM[2'h2][19:17];	// swap.scala:6:7, :98:41
        x_two_cycles_ago_0 = _RANDOM[2'h2][22:20];	// swap.scala:6:7, :98:{33,41}
        x_two_cycles_ago_1 = _RANDOM[2'h2][25:23];	// swap.scala:6:7, :98:{33,41}
        x_two_cycles_ago_2 = _RANDOM[2'h2][28:26];	// swap.scala:6:7, :98:{33,41}
        x_two_cycles_ago_3 = _RANDOM[2'h2][31:29];	// swap.scala:6:7, :98:{33,41}
        x_two_cycles_ago_4 = _RANDOM[2'h3][2:0];	// swap.scala:6:7, :98:33
        x_two_cycles_ago_5 = _RANDOM[2'h3][5:3];	// swap.scala:6:7, :98:33
        x_two_cycles_ago_6 = _RANDOM[2'h3][8:6];	// swap.scala:6:7, :98:33
        x_two_cycles_ago_7 = _RANDOM[2'h3][11:9];	// swap.scala:6:7, :98:33
        p_two_cycles_ago_REG = _RANDOM[2'h3][14:12];	// swap.scala:6:7, :98:33, :99:41
        p_two_cycles_ago = _RANDOM[2'h3][17:15];	// swap.scala:6:7, :98:33, :99:33
        m_two_cycles_ago_REG = _RANDOM[2'h3][20:18];	// swap.scala:6:7, :98:33, :100:41
        m_two_cycles_ago = _RANDOM[2'h3][23:21];	// swap.scala:6:7, :98:33, :100:33
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// swap.scala:6:7
      `FIRRTL_AFTER_INITIAL	// swap.scala:6:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (_resetCounter_timeSinceReset),
    .notChaos       (_resetCounter_notChaos)
  );
  assign io_x_out_0 = x_0;	// swap.scala:6:7, :17:18
  assign io_x_out_1 = x_1;	// swap.scala:6:7, :17:18
  assign io_x_out_2 = x_2;	// swap.scala:6:7, :17:18
  assign io_x_out_3 = x_3;	// swap.scala:6:7, :17:18
  assign io_x_out_4 = x_4;	// swap.scala:6:7, :17:18
  assign io_x_out_5 = x_5;	// swap.scala:6:7, :17:18
  assign io_x_out_6 = x_6;	// swap.scala:6:7, :17:18
  assign io_x_out_7 = x_7;	// swap.scala:6:7, :17:18
  assign io_tmp_out = tmp;	// swap.scala:6:7, :20:20
  assign io_p_out = p;	// swap.scala:6:7, :27:11
  assign io_m_out = m;	// swap.scala:6:7, :28:11
endmodule


// ----- 8< ----- FILE "./ResetCounter.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.1

module ResetCounter(
    input clk,
    input reset,
    output [31:0] timeSinceReset,
    output notChaos
);

reg [31:0] count;
reg flag;
initial begin
  count = 0;
  flag = 0;
end

assign timeSinceReset = count;
assign notChaos = flag;

always @(posedge clk) begin
    if (reset) begin
        count <= 0;
        flag <= 1;
    end else if (flag) begin
        count <= count + 1;
    end
end

endmodule
    

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----
