// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module ResetCounter

module LFSR(	// gigamax.scala:35:7
  input         clock,	// gigamax.scala:35:7
                reset,	// gigamax.scala:35:7
  output [15:0] io_out	// gigamax.scala:36:14
);

  reg [15:0] lfsrReg;	// gigamax.scala:40:24
  always @(posedge clock) begin	// gigamax.scala:35:7
    if (reset)	// gigamax.scala:35:7
      lfsrReg <= 16'h1;	// gigamax.scala:40:24
    else	// gigamax.scala:35:7
      lfsrReg <= {lfsrReg[14:0], lfsrReg[15] ^ lfsrReg[14] ^ lfsrReg[13] ^ lfsrReg[11]};	// gigamax.scala:40:24, :43:{17,25,45,64,83,93,102}
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// gigamax.scala:35:7
    `ifdef FIRRTL_BEFORE_INITIAL	// gigamax.scala:35:7
      `FIRRTL_BEFORE_INITIAL	// gigamax.scala:35:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// gigamax.scala:35:7
      automatic logic [31:0] _RANDOM[0:0];	// gigamax.scala:35:7
      `ifdef INIT_RANDOM_PROLOG_	// gigamax.scala:35:7
        `INIT_RANDOM_PROLOG_	// gigamax.scala:35:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// gigamax.scala:35:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// gigamax.scala:35:7
        lfsrReg = _RANDOM[/*Zero width*/ 1'b0][15:0];	// gigamax.scala:35:7, :40:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// gigamax.scala:35:7
      `FIRRTL_AFTER_INITIAL	// gigamax.scala:35:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out = lfsrReg;	// gigamax.scala:35:7, :40:24
endmodule

module BusDevice(	// gigamax.scala:160:7
  input        clock,	// gigamax.scala:160:7
               reset,	// gigamax.scala:160:7
  input  [3:0] io_CMD,	// gigamax.scala:161:14
  input        io_master,	// gigamax.scala:161:14
               io_REPLY_STALL,	// gigamax.scala:161:14
               io_REPLY_WAITING,	// gigamax.scala:161:14
  output       io_waiting,	// gigamax.scala:161:14
               io_reply_waiting,	// gigamax.scala:161:14
               io_abort	// gigamax.scala:161:14
);

  reg  waitingReg;	// gigamax.scala:163:27
  wire io_reply_waiting_0 = ~io_master & waitingReg;	// gigamax.scala:163:27, :166:{23,34}
  wire _io_abort_T = io_CMD == 4'h1;	// gigamax.scala:168:24
  wire _io_abort_T_1 = io_CMD == 4'h2;	// gigamax.scala:168:58
  wire io_abort_0 = io_REPLY_STALL | (_io_abort_T | _io_abort_T_1) & io_REPLY_WAITING;	// gigamax.scala:167:30, :168:{24,48,58,82}
  wire _GEN = io_CMD == 4'h8;	// gigamax.scala:176:35
  reg  hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// gigamax.scala:160:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  BusDevice3A_Reply_waiting_signal_mismatch:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     io_reply_waiting_0 == (~io_master & waitingReg));	// gigamax.scala:163:27, :166:{23,34}, :187:{29,45}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  BusDevice3A_Abort_should_be_true_when_REPLY_STALL_is_true:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~io_REPLY_STALL | io_abort_0);	// gigamax.scala:167:30, :191:{12,28}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  BusDevice3A_Abort_should_be_true_for_read_commands_with_REPLY_WAITING:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~((_io_abort_T | _io_abort_T_1) & io_REPLY_WAITING) | io_abort_0);	// gigamax.scala:167:30, :168:{24,58}, :195:{12,46,80,101}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  BusDevice3A_Waiting_should_be_cleared_after_response:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     waitingReg & ~io_master & _GEN |-> ##[1:10] ~waitingReg);	// gigamax.scala:163:27, :166:23, :176:35, :199:47, :200:22, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// gigamax.scala:160:7
    if (reset) begin	// gigamax.scala:160:7
      hasBeenResetReg <= 1'h1;	// gigamax.scala:160:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
      waitingReg <= 1'h0;	// gigamax.scala:160:7, :163:27
    end
    else if (~io_abort_0)	// gigamax.scala:167:30
      waitingReg <=
        io_master & _io_abort_T | io_master & _io_abort_T_1
        | ~(~io_master & _GEN | ~io_master & io_CMD == 4'h5 | ~io_master & io_CMD == 4'h6)
        & waitingReg;	// gigamax.scala:163:27, :166:23, :168:{24,58}, :172:{24,59}, :173:16, :174:{24,58}, :175:16, :176:{25,35,57}, :177:16, :178:{25,35,67}, :179:16, :180:{25,35,66}, :181:16
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// gigamax.scala:160:7
    `ifdef FIRRTL_BEFORE_INITIAL	// gigamax.scala:160:7
      `FIRRTL_BEFORE_INITIAL	// gigamax.scala:160:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// gigamax.scala:160:7
      automatic logic [31:0] _RANDOM[0:0];	// gigamax.scala:160:7
      `ifdef INIT_RANDOM_PROLOG_	// gigamax.scala:160:7
        `INIT_RANDOM_PROLOG_	// gigamax.scala:160:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// gigamax.scala:160:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// gigamax.scala:160:7
        waitingReg = _RANDOM[/*Zero width*/ 1'b0][0];	// gigamax.scala:160:7, :163:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// gigamax.scala:160:7
      `FIRRTL_AFTER_INITIAL	// gigamax.scala:160:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  assign io_waiting = waitingReg;	// gigamax.scala:160:7, :163:27
  assign io_reply_waiting = io_reply_waiting_0;	// gigamax.scala:160:7, :166:34
  assign io_abort = io_abort_0;	// gigamax.scala:160:7, :167:30
endmodule

module CacheDevice(	// gigamax.scala:60:7
  input        clock,	// gigamax.scala:60:7
               reset,	// gigamax.scala:60:7
  input  [3:0] io_CMD,	// gigamax.scala:61:14
  input        io_master,	// gigamax.scala:61:14
               io_abort,	// gigamax.scala:61:14
               io_waiting,	// gigamax.scala:61:14
  output [1:0] io_state,	// gigamax.scala:61:14
               io_snoop,	// gigamax.scala:61:14
  output       io_reply_owned	// gigamax.scala:61:14
);

  wire [15:0] _lfsr_io_out;	// gigamax.scala:64:20
  reg  [1:0]  stateReg;	// gigamax.scala:67:25
  reg  [1:0]  snoopReg;	// gigamax.scala:68:25
  wire        _nond_state_T = stateReg == 2'h1;	// gigamax.scala:67:25, :75:29, :81:8
  wire        _nond_snoop_T_1 = stateReg == 2'h2;	// gigamax.scala:67:25, :75:61
  wire        io_reply_owned_0 = ~io_master & _nond_snoop_T_1;	// gigamax.scala:75:61, :77:{22,34}
  wire        _GEN = ~io_master & _nond_snoop_T_1;	// gigamax.scala:75:61, :77:22, :94:21
  wire        _GEN_0 = stateReg == 2'h0;	// gigamax.scala:67:25, :80:23, :125:21
  reg         hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire        hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// gigamax.scala:60:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  CacheDevice3A_Invalid_state_value:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     _GEN_0 | _nond_state_T | _nond_snoop_T_1);	// gigamax.scala:75:{29,61}, :125:{21,70}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  CacheDevice3A_Invalid_snoop_value:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     snoopReg == 2'h0 | snoopReg == 2'h1 | snoopReg == 2'h2);	// gigamax.scala:68:25, :75:61, :80:23, :81:8, :129:{21,52,70,82}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  CacheDevice3A_Readable_signal_mismatch:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ((_nond_state_T | _nond_snoop_T_1)
                      & ~io_waiting) == ((_nond_state_T | _nond_snoop_T_1)
                                         & ~io_waiting));	// gigamax.scala:75:{29,48,61,80,83}, :133:{24,57,87}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  CacheDevice3A_Writable_signal_mismatch:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     (_nond_snoop_T_1 & ~io_waiting) == (_nond_snoop_T_1 & ~io_waiting));	// gigamax.scala:75:{61,83}, :76:46, :135:{24,55}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  CacheDevice3A_Reply_owned_signal_mismatch:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     io_reply_owned_0 == _GEN);	// gigamax.scala:77:34, :94:21, :139:27, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  CacheDevice3A_Invalid_state_transition_from_invalid:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_GEN_0 & io_master & io_CMD != 4'h1 & io_CMD != 4'h2
                       & io_CMD != 4'h3 & io_CMD != 4'h4 & io_CMD != 4'h5
                       & io_CMD != 4'h6));	// gigamax.scala:80:74, :96:36, :98:36, :106:22, :125:21, :143:12, :144:{20,54}, :145:{20,56}, :146:{20,51,61}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// gigamax.scala:60:7
    if (reset) begin	// gigamax.scala:60:7
      hasBeenResetReg <= 1'h1;	// gigamax.scala:60:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
      stateReg <= 2'h0;	// gigamax.scala:67:25, :80:23
      snoopReg <= 2'h0;	// gigamax.scala:68:25, :80:23
    end
    else if (io_abort) begin	// gigamax.scala:61:14
    end
    else begin	// gigamax.scala:61:14
      automatic logic _nond_snoop_T_3;	// gigamax.scala:80:74
      automatic logic _GEN_1;	// gigamax.scala:96:36
      automatic logic _GEN_2;	// gigamax.scala:98:36
      automatic logic _GEN_3;	// gigamax.scala:106:22
      _nond_snoop_T_3 = io_CMD == 4'h1;	// gigamax.scala:80:74
      _GEN_1 = io_CMD == 4'h5;	// gigamax.scala:96:36
      _GEN_2 = io_CMD == 4'h6;	// gigamax.scala:98:36
      _GEN_3 = io_CMD == 4'h2;	// gigamax.scala:106:22
      if (io_master) begin	// gigamax.scala:61:14
        if (io_CMD == 4'h1)	// gigamax.scala:80:74, :106:22
          stateReg <= 2'h1;	// gigamax.scala:67:25, :81:8
        else if (_GEN_3)	// gigamax.scala:106:22
          stateReg <= 2'h2;	// gigamax.scala:67:25, :75:61
        else if (io_CMD == 4'h3 | _GEN_1)	// gigamax.scala:96:36, :106:22, :109:46, :110:51
          stateReg <= 2'h0;	// gigamax.scala:67:25, :80:23
        else if (io_CMD == 4'h4 | _GEN_2)	// gigamax.scala:67:25, :98:36, :106:22, :111:45, :112:50
          stateReg <= 2'h1;	// gigamax.scala:67:25, :81:8
      end
      else if (~io_master & _nond_state_T & (_GEN_3 | io_CMD == 4'h7))	// gigamax.scala:75:29, :77:22, :106:22, :114:57, :115:{46,56}
        stateReg <= 2'h0;	// gigamax.scala:67:25, :80:23
      else if (_nond_state_T)	// gigamax.scala:75:29
        stateReg <= {1'h0, _nond_state_T & _lfsr_io_out[1]};	// gigamax.scala:60:7, :64:20, :67:25, :75:29, :84:23, :85:20, :117:44, :118:16
      if (_GEN & _nond_snoop_T_3)	// gigamax.scala:80:74, :94:{21,50}
        snoopReg <=
          ~io_master & _nond_snoop_T_1 & _nond_snoop_T_3
            ? (_lfsr_io_out[0] ? 2'h1 : 2'h2)
            : 2'h0;	// gigamax.scala:64:20, :68:25, :75:61, :77:22, :80:{23,64,74}, :81:{8,20}
      else if (io_master & _GEN_1 | io_master & _GEN_2)	// gigamax.scala:96:{26,36,68}, :97:16, :98:{26,36,67}, :99:16, :101:16
        snoopReg <= 2'h0;	// gigamax.scala:68:25, :80:23
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// gigamax.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// gigamax.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// gigamax.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// gigamax.scala:60:7
      automatic logic [31:0] _RANDOM[0:0];	// gigamax.scala:60:7
      `ifdef INIT_RANDOM_PROLOG_	// gigamax.scala:60:7
        `INIT_RANDOM_PROLOG_	// gigamax.scala:60:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// gigamax.scala:60:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// gigamax.scala:60:7
        stateReg = _RANDOM[/*Zero width*/ 1'b0][1:0];	// gigamax.scala:60:7, :67:25
        snoopReg = _RANDOM[/*Zero width*/ 1'b0][3:2];	// gigamax.scala:60:7, :67:25, :68:25
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// gigamax.scala:60:7
      `FIRRTL_AFTER_INITIAL	// gigamax.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  LFSR lfsr (	// gigamax.scala:64:20
    .clock  (clock),
    .reset  (reset),
    .io_out (_lfsr_io_out)
  );
  assign io_state = stateReg;	// gigamax.scala:60:7, :67:25
  assign io_snoop = snoopReg;	// gigamax.scala:60:7, :68:25
  assign io_reply_owned = io_reply_owned_0;	// gigamax.scala:60:7, :77:34
endmodule

module Processor(	// gigamax.scala:215:7
  input        clock,	// gigamax.scala:215:7
               reset,	// gigamax.scala:215:7
  input  [3:0] io_CMD,	// gigamax.scala:216:14
  input        io_master,	// gigamax.scala:216:14
               io_REPLY_WAITING,	// gigamax.scala:216:14
               io_REPLY_STALL,	// gigamax.scala:216:14
  output [3:0] io_cmd,	// gigamax.scala:216:14
  output       io_reply_owned,	// gigamax.scala:216:14
               io_reply_waiting,	// gigamax.scala:216:14
               io_reply_stall	// gigamax.scala:216:14
);

  wire [1:0]  _cacheDevice_io_state;	// gigamax.scala:232:27
  wire [1:0]  _cacheDevice_io_snoop;	// gigamax.scala:232:27
  wire        _busDevice_io_waiting;	// gigamax.scala:222:25
  wire        _busDevice_io_abort;	// gigamax.scala:222:25
  wire [15:0] _lfsr_io_out;	// gigamax.scala:219:20
  wire        _io_cmd_T_12 = _cacheDevice_io_state == 2'h2;	// gigamax.scala:232:27, :242:21, :247:30
  wire [2:0]  _io_cmd_T_20 =
    io_master & ~(|_cacheDevice_io_state)
      ? {1'h0, _lfsr_io_out[2] ? 2'h1 : 2'h2}
      : io_master & _cacheDevice_io_state == 2'h1
          ? 3'h2
          : io_master & _io_cmd_T_12 & _cacheDevice_io_snoop == 2'h2
              ? 3'h5
              : io_master & _io_cmd_T_12 & _cacheDevice_io_snoop == 2'h1
                  ? 3'h6
                  : {1'h0, {2{io_master & _io_cmd_T_12 & _cacheDevice_io_snoop == 2'h0}}};	// gigamax.scala:219:20, :232:27, :242:{21,33}, :245:{16,27,36}, :246:{8,19,28}, :247:{10,30,47,56}, :248:{12,49,58}, :249:{14,51,60}
  wire [3:0]  io_cmd_0 = {1'h0, _io_cmd_T_20};	// gigamax.scala:245:{10,16}, :246:28
  reg         hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  always @(posedge clock) begin	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    if (reset)	// src/main/scala/chisel3/ltl/LTL.scala:362:39
      hasBeenResetReg <= 1'h1;	// gigamax.scala:242:21, src/main/scala/chisel3/ltl/LTL.scala:362:39
  end // always @(posedge)
  wire        hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// gigamax.scala:242:21, :246:28, src/main/scala/chisel3/ltl/LTL.scala:362:39
  Processor3A_Invalid_command_value:
    assert property (@(posedge clock) disable iff (~hasBeenReset) io_cmd_0 < 4'h9);	// gigamax.scala:245:10, :258:19, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Processor3A_Non2Dmaster_should_only_issue_idle:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     io_master | _io_cmd_T_20 == 3'h0);	// gigamax.scala:245:16, :261:{22,32}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Processor3A_Master_with_invalid_state_should_issue_read_commands:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~io_master | (|_cacheDevice_io_state) | _io_cmd_T_20 == 3'h1
                     | _io_cmd_T_20 == 3'h2);	// gigamax.scala:232:27, :245:{16,36}, :246:8, :264:{12,51}, :265:{20,54}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  LFSR lfsr (	// gigamax.scala:219:20
    .clock  (clock),
    .reset  (reset),
    .io_out (_lfsr_io_out)
  );
  BusDevice busDevice (	// gigamax.scala:222:25
    .clock            (clock),
    .reset            (reset),
    .io_CMD           (io_CMD),
    .io_master        (io_master),
    .io_REPLY_STALL   (io_REPLY_STALL),
    .io_REPLY_WAITING (io_REPLY_WAITING),
    .io_waiting       (_busDevice_io_waiting),
    .io_reply_waiting (io_reply_waiting),
    .io_abort         (_busDevice_io_abort)
  );
  CacheDevice cacheDevice (	// gigamax.scala:232:27
    .clock          (clock),
    .reset          (reset),
    .io_CMD         (io_CMD),
    .io_master      (io_master),
    .io_abort       (_busDevice_io_abort),	// gigamax.scala:222:25
    .io_waiting     (_busDevice_io_waiting),	// gigamax.scala:222:25
    .io_state       (_cacheDevice_io_state),
    .io_snoop       (_cacheDevice_io_snoop),
    .io_reply_owned (io_reply_owned)
  );
  assign io_cmd = io_cmd_0;	// gigamax.scala:215:7, :245:10
  assign io_reply_stall = _lfsr_io_out[3];	// gigamax.scala:215:7, :219:20, :253:32
endmodule

module Memory(	// gigamax.scala:281:7
  input        clock,	// gigamax.scala:281:7
               reset,	// gigamax.scala:281:7
  input  [3:0] io_CMD,	// gigamax.scala:282:14
  input        io_master,	// gigamax.scala:282:14
               io_REPLY_OWNED,	// gigamax.scala:282:14
               io_REPLY_WAITING,	// gigamax.scala:282:14
               io_REPLY_STALL,	// gigamax.scala:282:14
  output [3:0] io_cmd,	// gigamax.scala:282:14
  output       io_reply_stall	// gigamax.scala:282:14
);

  wire [15:0] _lfsr_io_out;	// gigamax.scala:285:20
  reg         busyReg;	// gigamax.scala:287:24
  wire        _io_reply_stall_T = io_CMD == 4'h1;	// gigamax.scala:293:23
  wire        _io_reply_stall_T_1 = io_CMD == 4'h2;	// gigamax.scala:293:57
  wire        _GEN = io_master & busyReg & _lfsr_io_out[4];	// gigamax.scala:285:20, :287:24, :296:{21,33}, :299:16
  wire        _io_reply_stall_T_3 = io_CMD == 4'h3;	// gigamax.scala:302:30
  wire        _io_reply_stall_T_5 = io_CMD == 4'h4;	// gigamax.scala:302:66
  wire        _io_reply_stall_T_7 = io_CMD == 4'h5;	// gigamax.scala:303:30
  wire        _io_reply_stall_T_9 = io_CMD == 4'h6;	// gigamax.scala:303:71
  wire        io_reply_stall_0 =
    busyReg
    & (_io_reply_stall_T | _io_reply_stall_T_1 | _io_reply_stall_T_3 | _io_reply_stall_T_5
       | _io_reply_stall_T_7 | _io_reply_stall_T_9) | _lfsr_io_out[5];	// gigamax.scala:285:20, :287:24, :293:{23,57}, :297:37, :301:{24,33}, :302:{30,66}, :303:{30,61,71}
  reg         hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire        hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// gigamax.scala:281:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  Memory3A_Should_never_claim_reply_owned:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// gigamax.scala:281:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Memory3A_Should_never_claim_reply_waiting:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// gigamax.scala:281:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Memory3A_Busy_master_should_only_issue_response_or_idle:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// gigamax.scala:281:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Memory3A_Non2Dmaster_non2Dbusy_should_only_issue_idle:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     io_master | busyReg | ~_GEN);	// gigamax.scala:287:24, :296:21, :299:16, :323:77, :327:33, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Memory3A_Should_stall_when_busy_with_memory_commands:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~busyReg
                     | ~(_io_reply_stall_T | _io_reply_stall_T_1 | _io_reply_stall_T_3
                         | _io_reply_stall_T_5 | _io_reply_stall_T_7
                         | _io_reply_stall_T_9) | io_reply_stall_0);	// gigamax.scala:287:24, :293:{23,57}, :301:24, :302:{30,66}, :303:{30,71}, :323:12, :331:24, :333:{50,91}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// gigamax.scala:281:7
    if (reset) begin	// gigamax.scala:281:7
      hasBeenResetReg <= 1'h1;	// gigamax.scala:281:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
      busyReg <= 1'h0;	// gigamax.scala:281:7, :287:24
    end
    else if (~(io_REPLY_STALL | (_io_reply_stall_T | _io_reply_stall_T_1)
               & io_REPLY_WAITING | (_io_reply_stall_T | _io_reply_stall_T_1)
               & io_REPLY_OWNED))	// gigamax.scala:293:{23,47,57,81,101}, :294:{47,81}
      busyReg <=
        ~(io_master & io_CMD == 4'h8)
        & (~io_master & (_io_reply_stall_T_1 | _io_reply_stall_T) | busyReg);	// gigamax.scala:287:24, :293:{23,57}, :296:21, :308:{24,34,56}, :309:13, :310:{14,25,59,95}, :311:13
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// gigamax.scala:281:7
    `ifdef FIRRTL_BEFORE_INITIAL	// gigamax.scala:281:7
      `FIRRTL_BEFORE_INITIAL	// gigamax.scala:281:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// gigamax.scala:281:7
      automatic logic [31:0] _RANDOM[0:0];	// gigamax.scala:281:7
      `ifdef INIT_RANDOM_PROLOG_	// gigamax.scala:281:7
        `INIT_RANDOM_PROLOG_	// gigamax.scala:281:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// gigamax.scala:281:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// gigamax.scala:281:7
        busyReg = _RANDOM[/*Zero width*/ 1'b0][0];	// gigamax.scala:281:7, :287:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// gigamax.scala:281:7
      `FIRRTL_AFTER_INITIAL	// gigamax.scala:281:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  LFSR lfsr (	// gigamax.scala:285:20
    .clock  (clock),
    .reset  (reset),
    .io_out (_lfsr_io_out)
  );
  assign io_cmd = {_GEN, 3'h0};	// gigamax.scala:281:7, :296:21, :299:16
  assign io_reply_stall = io_reply_stall_0;	// gigamax.scala:281:7, :301:24
endmodule

module Main(	// gigamax.scala:353:7
  input        clock,	// gigamax.scala:353:7
               reset,	// gigamax.scala:353:7
  output [3:0] io_p0_cmd,	// gigamax.scala:354:14
               io_p1_cmd,	// gigamax.scala:354:14
               io_p2_cmd,	// gigamax.scala:354:14
               io_m_cmd,	// gigamax.scala:354:14
  output       io_p0_master,	// gigamax.scala:354:14
               io_p1_master,	// gigamax.scala:354:14
               io_p2_master,	// gigamax.scala:354:14
               io_m_master,	// gigamax.scala:354:14
  output [3:0] io_CMD,	// gigamax.scala:354:14
  output       io_REPLY_OWNED,	// gigamax.scala:354:14
               io_REPLY_WAITING,	// gigamax.scala:354:14
               io_REPLY_STALL	// gigamax.scala:354:14
);

  wire [3:0]  _m_io_cmd;	// gigamax.scala:363:17
  wire        _m_io_reply_stall;	// gigamax.scala:363:17
  wire [3:0]  _p2_io_cmd;	// gigamax.scala:362:18
  wire        _p2_io_reply_owned;	// gigamax.scala:362:18
  wire        _p2_io_reply_waiting;	// gigamax.scala:362:18
  wire        _p2_io_reply_stall;	// gigamax.scala:362:18
  wire [3:0]  _p1_io_cmd;	// gigamax.scala:361:18
  wire        _p1_io_reply_owned;	// gigamax.scala:361:18
  wire        _p1_io_reply_waiting;	// gigamax.scala:361:18
  wire        _p1_io_reply_stall;	// gigamax.scala:361:18
  wire [3:0]  _p0_io_cmd;	// gigamax.scala:360:18
  wire        _p0_io_reply_owned;	// gigamax.scala:360:18
  wire        _p0_io_reply_waiting;	// gigamax.scala:360:18
  wire        _p0_io_reply_stall;	// gigamax.scala:360:18
  wire [15:0] _lfsr_io_out;	// gigamax.scala:357:20
  wire        _REPLY_OWNED_T = _p0_io_reply_owned | _p1_io_reply_owned;	// gigamax.scala:360:18, :361:18, :404:36
  wire        REPLY_OWNED = _REPLY_OWNED_T | _p2_io_reply_owned;	// gigamax.scala:362:18, :404:{36,56}
  wire        REPLY_WAITING =
    _p0_io_reply_waiting | _p1_io_reply_waiting | _p2_io_reply_waiting;	// gigamax.scala:360:18, :361:18, :362:18, :405:62
  wire        REPLY_STALL =
    _p0_io_reply_stall | _p1_io_reply_stall | _p2_io_reply_stall | _m_io_reply_stall;	// gigamax.scala:360:18, :361:18, :362:18, :363:17, :406:76
  wire        _CMD_T_18 = _p2_io_cmd == 4'h0;	// gigamax.scala:362:18, :412:{24,54}
  wire        _CMD_T_13 = _m_io_cmd == 4'h0;	// gigamax.scala:363:17, :412:{24,83}
  wire [3:0]  CMD =
    ~(|_p1_io_cmd) & _CMD_T_18 & _CMD_T_13
      ? _p0_io_cmd
      : ~(|_p0_io_cmd) & _CMD_T_18 & _CMD_T_13
          ? _p1_io_cmd
          : ~(|_p0_io_cmd) & ~(|_p1_io_cmd) & _CMD_T_13
              ? _p2_io_cmd
              : ~(|_p0_io_cmd) & ~(|_p1_io_cmd) & _CMD_T_18
                  ? _m_io_cmd
                  : _lfsr_io_out[7:4];	// gigamax.scala:357:20, :360:18, :361:18, :362:18, :363:17, :410:26, :412:{13,24,54,71,83}, :413:{8,19,66}, :414:{10,68}, :415:{12,70}
  wire        p1_master = ~(_lfsr_io_out[8]) & _lfsr_io_out[9];	// gigamax.scala:357:20, :419:27, :420:{19,51}
  wire        _m_master_T = _lfsr_io_out[8] | p1_master;	// gigamax.scala:357:20, :419:27, :420:19, :421:30
  wire        p2_master = ~_m_master_T & _lfsr_io_out[10];	// gigamax.scala:357:20, :421:{19,30,64}
  wire        m_master = ~(_m_master_T | p2_master) & _lfsr_io_out[11];	// gigamax.scala:357:20, :421:{19,30}, :422:{18,42,76}
  reg         hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  always @(posedge clock) begin	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    if (reset)	// src/main/scala/chisel3/ltl/LTL.scala:362:39
      hasBeenResetReg <= 1'h1;	// gigamax.scala:441:14, src/main/scala/chisel3/ltl/LTL.scala:362:39
  end // always @(posedge)
  wire        hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// gigamax.scala:412:24, :441:14, src/main/scala/chisel3/ltl/LTL.scala:362:39
  Main3A_Multiple_masters_active:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     {1'h0, {1'h0, _lfsr_io_out[8]} + {1'h0, p1_master}}
                     + {1'h0, {1'h0, p2_master} + {1'h0, m_master}} < 3'h2);	// gigamax.scala:357:20, :412:24, :419:27, :420:19, :421:19, :422:18, :441:14, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Main3A_Invalid_global_command:
    assert property (@(posedge clock) disable iff (~hasBeenReset) CMD < 4'h9);	// gigamax.scala:412:13, :444:16, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire        _GEN = _m_master_T | p2_master;	// gigamax.scala:421:{19,30}, :447:37
  Main3A_Memory_should_not_be_master_when_processor_is_master:
    assert property (@(posedge clock) disable iff (~hasBeenReset) ~_GEN | ~m_master);	// gigamax.scala:422:18, :447:{12,37,51,54}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Main3A_All_processors_should_be_non2Dmaster_when_memory_is_master:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~m_master | ~(_lfsr_io_out[8]) & ~p1_master & ~p2_master);	// gigamax.scala:357:20, :419:27, :420:19, :421:19, :422:18, :447:54, :451:{22,26,40,51,54}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Main3A_System_should_eventually_have_a_master:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1 |-> ##[1:20]
                     _GEN | m_master);	// gigamax.scala:422:18, :441:14, :447:37, :455:66, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  Main3A_Reply_owned_should_only_come_from_processors:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     REPLY_OWNED == (_REPLY_OWNED_T | _p2_io_reply_owned));	// gigamax.scala:362:18, :404:{36,56}, :459:{24,68}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Main3A_Command_arbitration_should_pick_valid_command:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~((|_p0_io_cmd) & (|_p1_io_cmd)) | CMD == _p0_io_cmd
                     | CMD == _p1_io_cmd | CMD == _lfsr_io_out[7:4]);	// gigamax.scala:357:20, :360:18, :361:18, :410:26, :412:{13,24}, :413:19, :463:{12,41,72}, :464:{17,38,59}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  LFSR lfsr (	// gigamax.scala:357:20
    .clock  (clock),
    .reset  (reset),
    .io_out (_lfsr_io_out)
  );
  Processor p0 (	// gigamax.scala:360:18
    .clock            (clock),
    .reset            (reset),
    .io_CMD           (CMD),	// gigamax.scala:412:13
    .io_master        (_lfsr_io_out[8]),	// gigamax.scala:357:20, :419:27
    .io_REPLY_WAITING (REPLY_WAITING),	// gigamax.scala:405:62
    .io_REPLY_STALL   (REPLY_STALL),	// gigamax.scala:406:76
    .io_cmd           (_p0_io_cmd),
    .io_reply_owned   (_p0_io_reply_owned),
    .io_reply_waiting (_p0_io_reply_waiting),
    .io_reply_stall   (_p0_io_reply_stall)
  );
  Processor p1 (	// gigamax.scala:361:18
    .clock            (clock),
    .reset            (reset),
    .io_CMD           (CMD),	// gigamax.scala:412:13
    .io_master        (p1_master),	// gigamax.scala:420:19
    .io_REPLY_WAITING (REPLY_WAITING),	// gigamax.scala:405:62
    .io_REPLY_STALL   (REPLY_STALL),	// gigamax.scala:406:76
    .io_cmd           (_p1_io_cmd),
    .io_reply_owned   (_p1_io_reply_owned),
    .io_reply_waiting (_p1_io_reply_waiting),
    .io_reply_stall   (_p1_io_reply_stall)
  );
  Processor p2 (	// gigamax.scala:362:18
    .clock            (clock),
    .reset            (reset),
    .io_CMD           (CMD),	// gigamax.scala:412:13
    .io_master        (p2_master),	// gigamax.scala:421:19
    .io_REPLY_WAITING (REPLY_WAITING),	// gigamax.scala:405:62
    .io_REPLY_STALL   (REPLY_STALL),	// gigamax.scala:406:76
    .io_cmd           (_p2_io_cmd),
    .io_reply_owned   (_p2_io_reply_owned),
    .io_reply_waiting (_p2_io_reply_waiting),
    .io_reply_stall   (_p2_io_reply_stall)
  );
  Memory m (	// gigamax.scala:363:17
    .clock            (clock),
    .reset            (reset),
    .io_CMD           (CMD),	// gigamax.scala:412:13
    .io_master        (m_master),	// gigamax.scala:422:18
    .io_REPLY_OWNED   (REPLY_OWNED),	// gigamax.scala:404:56
    .io_REPLY_WAITING (REPLY_WAITING),	// gigamax.scala:405:62
    .io_REPLY_STALL   (REPLY_STALL),	// gigamax.scala:406:76
    .io_cmd           (_m_io_cmd),
    .io_reply_stall   (_m_io_reply_stall)
  );
  assign io_p0_cmd = _p0_io_cmd;	// gigamax.scala:353:7, :360:18
  assign io_p1_cmd = _p1_io_cmd;	// gigamax.scala:353:7, :361:18
  assign io_p2_cmd = _p2_io_cmd;	// gigamax.scala:353:7, :362:18
  assign io_m_cmd = _m_io_cmd;	// gigamax.scala:353:7, :363:17
  assign io_p0_master = _lfsr_io_out[8];	// gigamax.scala:353:7, :357:20, :419:27
  assign io_p1_master = p1_master;	// gigamax.scala:353:7, :420:19
  assign io_p2_master = p2_master;	// gigamax.scala:353:7, :421:19
  assign io_m_master = m_master;	// gigamax.scala:353:7, :422:18
  assign io_CMD = CMD;	// gigamax.scala:353:7, :412:13
  assign io_REPLY_OWNED = REPLY_OWNED;	// gigamax.scala:353:7, :404:56
  assign io_REPLY_WAITING = REPLY_WAITING;	// gigamax.scala:353:7, :405:62
  assign io_REPLY_STALL = REPLY_STALL;	// gigamax.scala:353:7, :406:76
endmodule


// ----- 8< ----- FILE "./ResetCounter.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.1

module ResetCounter(
    input clk,
    input reset,
    output [31:0] timeSinceReset,
    output notChaos
);

reg [31:0] count;
reg flag;
initial begin
  count = 0;
  flag = 0;
end

assign timeSinceReset = count;
assign notChaos = flag;

always @(posedge clk) begin
    if (reset) begin
        count <= 0;
        flag <= 1;
    end else if (flag) begin
        count <= count + 1;
    end
end

endmodule
    

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----
