// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module ResetCounter

module short(	// short.scala:6:7
  input  clock,	// short.scala:6:7
         reset,	// short.scala:6:7
  output io_request	// short.scala:7:14
);

  reg        state;	// short.scala:15:22
  reg  [7:0] randomCounter;	// short.scala:18:30
  reg        hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire       hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// short.scala:6:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  State_should_always_be_valid:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// short.scala:6:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  reg        pastReady;	// short.scala:45:26
  reg        pastRequest;	// short.scala:46:28
  Ready_with_request_should_transition_to_busy:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(pastReady & pastRequest) | state);	// short.scala:15:22, :45:26, :46:28, :49:{12,24,40}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire       _GEN = state == ~(randomCounter[0]);	// short.scala:15:22, :18:30, :19:34, :22:{23,37}, :52:44
  Busy_state_transition_should_follow_nond_state:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN);	// short.scala:52:44, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Ready_without_request_should_follow_nond_state:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN);	// short.scala:52:44, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Should_eventually_leave_busy_state:
    assert property (@(posedge clock) disable iff (~hasBeenReset) state |-> ##[1:10]
                     ~state);	// short.scala:15:22, :58:44, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  reg        r;	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Delay.scala:11:20
  Request_should_be_stable_when_busy:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~state | randomCounter[1] == r);	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Delay.scala:11:20, short.scala:15:22, :18:30, :25:30, :58:44, :61:19, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// short.scala:6:7
    if (reset) begin	// short.scala:6:7
      hasBeenResetReg <= 1'h1;	// short.scala:6:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
      state <= 1'h0;	// short.scala:6:7, :15:22
      randomCounter <= 8'h0;	// short.scala:18:30
      pastReady <= 1'h0;	// short.scala:6:7, :45:26
      pastRequest <= 1'h0;	// short.scala:6:7, :46:28
    end
    else begin	// short.scala:6:7
      state <= ~state & randomCounter[1] | ~(randomCounter[0]);	// short.scala:15:22, :18:30, :19:34, :22:{23,37}, :25:30, :28:25, :29:22, :34:30
      randomCounter <= randomCounter + 8'h1;	// short.scala:18:30, :19:34
      pastReady <= ~state;	// short.scala:15:22, :28:14, :45:26
      pastRequest <= randomCounter[1];	// short.scala:18:30, :25:30, :46:28
    end
    r <= randomCounter[1];	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Delay.scala:11:20, short.scala:18:30, :25:30
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// short.scala:6:7
    `ifdef FIRRTL_BEFORE_INITIAL	// short.scala:6:7
      `FIRRTL_BEFORE_INITIAL	// short.scala:6:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// short.scala:6:7
      automatic logic [31:0] _RANDOM[0:0];	// short.scala:6:7
      `ifdef INIT_RANDOM_PROLOG_	// short.scala:6:7
        `INIT_RANDOM_PROLOG_	// short.scala:6:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// short.scala:6:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// short.scala:6:7
        state = _RANDOM[/*Zero width*/ 1'b0][0];	// short.scala:6:7, :15:22
        randomCounter = _RANDOM[/*Zero width*/ 1'b0][8:1];	// short.scala:6:7, :15:22, :18:30
        pastReady = _RANDOM[/*Zero width*/ 1'b0][9];	// short.scala:6:7, :15:22, :45:26
        pastRequest = _RANDOM[/*Zero width*/ 1'b0][10];	// short.scala:6:7, :15:22, :46:28
        r = _RANDOM[/*Zero width*/ 1'b0][13];	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Delay.scala:11:20, short.scala:6:7, :15:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// short.scala:6:7
      `FIRRTL_AFTER_INITIAL	// short.scala:6:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  assign io_request = randomCounter[1];	// short.scala:6:7, :18:30, :25:30
endmodule


// ----- 8< ----- FILE "./ResetCounter.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.1

module ResetCounter(
    input clk,
    input reset,
    output [31:0] timeSinceReset,
    output notChaos
);

reg [31:0] count;
reg flag;
initial begin
  count = 0;
  flag = 0;
end

assign timeSinceReset = count;
assign notChaos = flag;

always @(posedge clk) begin
    if (reset) begin
        count <= 0;
        flag <= 1;
    end else if (flag) begin
        count <= count + 1;
    end
end

endmodule
    

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----
