// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module ResetCounter

module reset(	// reset.scala:6:7
  input        clock,	// reset.scala:6:7
               reset,	// reset.scala:6:7
  input  [1:0] io_sel,	// reset.scala:7:14
  output [2:0] io_st	// reset.scala:7:14
);

  reg  st0;	// reset.scala:14:20
  reg  st1;	// reset.scala:15:20
  reg  st2;	// reset.scala:16:20
  reg  hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// reset.scala:6:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  During_reset2C_all_state_bits_should_be_0:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~reset | ~st0 & ~st1 & ~st2);	// reset.scala:14:20, :15:20, :16:20, :29:{12,26,34,49,57,64}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  st0_should_equal_sel5B05D_after_reset:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     reset | st0 == io_sel[0]);	// reset.scala:14:20, :19:16, :33:{25,38}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  st1_should_complement_every_cycle:
    assert property (@(posedge clock) disable iff (~hasBeenReset) reset | st1 == ~st1);	// reset.scala:15:20, :20:10, :38:{25,33}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  st2_should_be_valid_binary:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// reset.scala:6:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  st2_should_maintain_its_value_when_sel5B15D_is_0:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// reset.scala:6:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  When_sel5B15D_is_12C_st2_should_become_1:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     reset | ~(io_sel[1]) | st2);	// reset.scala:16:20, :21:16, :48:{25,39}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  When_sel5B15D_is_02C_st2_should_maintain_previous_value:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// reset.scala:6:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Output_st_should_always_be_within_32Dbit_range:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// reset.scala:6:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// reset.scala:6:7
    if (reset) begin	// reset.scala:6:7
      hasBeenResetReg <= 1'h1;	// reset.scala:6:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
      st0 <= 1'h0;	// reset.scala:6:7, :14:20
      st1 <= 1'h0;	// reset.scala:6:7, :15:20
      st2 <= 1'h0;	// reset.scala:6:7, :16:20
    end
    else begin	// reset.scala:6:7
      st0 <= io_sel[0];	// reset.scala:14:20, :19:16
      st1 <= ~st1;	// reset.scala:15:20, :20:10
      st2 <= io_sel[1] | st2;	// reset.scala:16:20, :21:{16,20}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// reset.scala:6:7
    `ifdef FIRRTL_BEFORE_INITIAL	// reset.scala:6:7
      `FIRRTL_BEFORE_INITIAL	// reset.scala:6:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// reset.scala:6:7
      automatic logic [31:0] _RANDOM[0:0];	// reset.scala:6:7
      `ifdef INIT_RANDOM_PROLOG_	// reset.scala:6:7
        `INIT_RANDOM_PROLOG_	// reset.scala:6:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// reset.scala:6:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// reset.scala:6:7
        st0 = _RANDOM[/*Zero width*/ 1'b0][0];	// reset.scala:6:7, :14:20
        st1 = _RANDOM[/*Zero width*/ 1'b0][1];	// reset.scala:6:7, :14:20, :15:20
        st2 = _RANDOM[/*Zero width*/ 1'b0][2];	// reset.scala:6:7, :14:20, :16:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// reset.scala:6:7
      `FIRRTL_AFTER_INITIAL	// reset.scala:6:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  assign io_st = {st2, st1, st0};	// reset.scala:6:7, :14:20, :15:20, :16:20, :24:15
endmodule


// ----- 8< ----- FILE "./ResetCounter.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.1

module ResetCounter(
    input clk,
    input reset,
    output [31:0] timeSinceReset,
    output notChaos
);

reg [31:0] count;
reg flag;
initial begin
  count = 0;
  flag = 0;
end

assign timeSinceReset = count;
assign notChaos = flag;

always @(posedge clk) begin
    if (reset) begin
        count <= 0;
        flag <= 1;
    end else if (flag) begin
        count <= count + 1;
    end
end

endmodule
    

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----
