// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module ResetCounter

module vcrc32_8(	// vcrc32_8.scala:7:7
  input         clock,	// vcrc32_8.scala:7:7
                reset,	// vcrc32_8.scala:7:7
                io_clken,	// vcrc32_8.scala:8:14
                io_reset,	// vcrc32_8.scala:8:14
                io_load,	// vcrc32_8.scala:8:14
                io_compute,	// vcrc32_8.scala:8:14
  input  [7:0]  io_data_in,	// vcrc32_8.scala:8:14
  output [7:0]  io_data_out,	// vcrc32_8.scala:8:14
  output        io_crc_ok,	// vcrc32_8.scala:8:14
  output [31:0] io_crc	// vcrc32_8.scala:8:14
);

  reg  [31:0] crcReg;	// vcrc32_8.scala:24:23
  wire [31:0] _newCrc_T_1 = {crcReg[23:0], io_data_in};	// vcrc32_8.scala:24:23, :77:{18,25}
  wire [7:0]  newCrc_x = crcReg[31:24] ^ io_data_in;	// vcrc32_8.scala:24:23, :28:{14,23}
  wire [31:0] _newCrc_T_2 =
    {newCrc_x[5] ^ crcReg[23],
     newCrc_x[4] ^ newCrc_x[7] ^ crcReg[22],
     newCrc_x[3] ^ newCrc_x[6] ^ newCrc_x[7] ^ crcReg[21],
     newCrc_x[2] ^ newCrc_x[5] ^ newCrc_x[6] ^ crcReg[20],
     newCrc_x[7] ^ newCrc_x[1] ^ newCrc_x[4] ^ newCrc_x[5] ^ crcReg[19],
     newCrc_x[6] ^ newCrc_x[0] ^ newCrc_x[3] ^ newCrc_x[4] ^ crcReg[18],
     newCrc_x[2] ^ newCrc_x[3] ^ crcReg[17],
     newCrc_x[7] ^ newCrc_x[1] ^ newCrc_x[2] ^ crcReg[16],
     newCrc_x[6] ^ newCrc_x[0] ^ newCrc_x[1] ^ crcReg[15],
     newCrc_x[0] ^ crcReg[14],
     newCrc_x[5] ^ crcReg[13],
     newCrc_x[4] ^ crcReg[12],
     newCrc_x[3] ^ newCrc_x[7] ^ crcReg[11],
     newCrc_x[2] ^ newCrc_x[6] ^ newCrc_x[7] ^ crcReg[10],
     newCrc_x[1] ^ newCrc_x[5] ^ newCrc_x[6] ^ crcReg[9],
     newCrc_x[0] ^ newCrc_x[4] ^ newCrc_x[5] ^ crcReg[8],
     newCrc_x[3] ^ newCrc_x[4] ^ newCrc_x[5] ^ newCrc_x[7] ^ crcReg[7],
     newCrc_x[2] ^ newCrc_x[3] ^ newCrc_x[4] ^ newCrc_x[6] ^ newCrc_x[7] ^ crcReg[6],
     newCrc_x[7] ^ newCrc_x[1] ^ newCrc_x[2] ^ newCrc_x[3] ^ newCrc_x[5] ^ newCrc_x[6]
       ^ crcReg[5],
     newCrc_x[6] ^ newCrc_x[0] ^ newCrc_x[1] ^ newCrc_x[2] ^ newCrc_x[4] ^ newCrc_x[5]
       ^ crcReg[4],
     newCrc_x[0] ^ newCrc_x[1] ^ newCrc_x[3] ^ newCrc_x[4] ^ crcReg[3],
     newCrc_x[0] ^ newCrc_x[2] ^ newCrc_x[3] ^ newCrc_x[5] ^ crcReg[2],
     newCrc_x[1] ^ newCrc_x[2] ^ newCrc_x[4] ^ newCrc_x[5] ^ crcReg[1],
     newCrc_x[0] ^ newCrc_x[1] ^ newCrc_x[3] ^ newCrc_x[4] ^ crcReg[0],
     newCrc_x[0] ^ newCrc_x[2] ^ newCrc_x[3] ^ newCrc_x[5] ^ newCrc_x[7],
     newCrc_x[1] ^ newCrc_x[2] ^ newCrc_x[4] ^ newCrc_x[5] ^ newCrc_x[6] ^ newCrc_x[7],
     newCrc_x[7] ^ newCrc_x[6] ^ newCrc_x[5] ^ newCrc_x[4] ^ newCrc_x[3] ^ newCrc_x[1]
       ^ newCrc_x[0],
     newCrc_x[6] ^ newCrc_x[4] ^ newCrc_x[3] ^ newCrc_x[2] ^ newCrc_x[0],
     newCrc_x[7] ^ newCrc_x[1] ^ newCrc_x[2] ^ newCrc_x[3],
     newCrc_x[6] ^ newCrc_x[0] ^ newCrc_x[7] ^ newCrc_x[1] ^ newCrc_x[2],
     newCrc_x[6] ^ newCrc_x[0] ^ newCrc_x[7] ^ newCrc_x[1],
     newCrc_x[6] ^ newCrc_x[0]};	// vcrc32_8.scala:24:23, :28:23, :32:{18,22,25}, :33:{18,25,29,32}, :34:{18,25,36,39}, :35:{18,36,39}, :36:{25,43,46}, :37:{25,43,46}, :38:{29,32}, :39:{36,39}, :40:{36,39}, :41:{22,25}, :42:{22,25}, :43:{22,25}, :44:{29,32}, :45:{36,39}, :46:{36,39}, :47:{36,39}, :48:{43,46}, :49:{50,53}, :50:{57,60}, :51:{57,60}, :52:{43,46}, :53:{43,46}, :54:{43,46}, :55:{43,46}, :56:43, :57:50, :58:57, :59:43, :60:36, :61:43, :62:36, :63:22, :65:8
  wire [31:0] newCrc =
    io_reset ? 32'hFFFFFFFF : io_load ? _newCrc_T_1 : io_compute ? _newCrc_T_2 : crcReg;	// vcrc32_8.scala:24:23, :65:8, :74:18, :75:12, :76:23, :77:{12,18}, :78:26, :79:12, :81:12
  reg         hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire        hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// src/main/scala/chisel3/ltl/LTL.scala:362:39, vcrc32_8.scala:7:7
  Reset_should_compute_CRC_initial_value:
    assert property (@(posedge clock) disable iff (~hasBeenReset) ~io_reset | (&newCrc));	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, vcrc32_8.scala:74:18, :75:12, :76:23, :97:{12,22,32}
  wire        _GEN = ~io_clken | io_reset;	// vcrc32_8.scala:100:{12,22}
  Load_operation_should_shift_data_into_CRC_register:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     _GEN | ~io_load | crcReg == {newCrc[23:0], io_data_in});	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, vcrc32_8.scala:24:23, :74:18, :75:12, :76:23, :100:{22,37,46,57,64,71}
  wire [7:0]  x = newCrc[31:24] ^ io_data_in;	// vcrc32_8.scala:28:{14,23}, :74:18, :75:12, :76:23
  Compute_operation_should_update_CRC_with_parallel_CRC_calculation:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     _GEN | io_load | ~io_compute
                     | crcReg == {x[5] ^ newCrc[23],
                                  x[4] ^ x[7] ^ newCrc[22],
                                  x[3] ^ x[6] ^ x[7] ^ newCrc[21],
                                  x[2] ^ x[5] ^ x[6] ^ newCrc[20],
                                  x[7] ^ x[1] ^ x[4] ^ x[5] ^ newCrc[19],
                                  x[6] ^ x[0] ^ x[3] ^ x[4] ^ newCrc[18],
                                  x[2] ^ x[3] ^ newCrc[17],
                                  x[7] ^ x[1] ^ x[2] ^ newCrc[16],
                                  x[6] ^ x[0] ^ x[1] ^ newCrc[15],
                                  x[0] ^ newCrc[14],
                                  x[5] ^ newCrc[13],
                                  x[4] ^ newCrc[12],
                                  x[3] ^ x[7] ^ newCrc[11],
                                  x[2] ^ x[6] ^ x[7] ^ newCrc[10],
                                  x[1] ^ x[5] ^ x[6] ^ newCrc[9],
                                  x[0] ^ x[4] ^ x[5] ^ newCrc[8],
                                  x[3] ^ x[4] ^ x[5] ^ x[7] ^ newCrc[7],
                                  x[2] ^ x[3] ^ x[4] ^ x[6] ^ x[7] ^ newCrc[6],
                                  x[7] ^ x[1] ^ x[2] ^ x[3] ^ x[5] ^ x[6] ^ newCrc[5],
                                  x[6] ^ x[0] ^ x[1] ^ x[2] ^ x[4] ^ x[5] ^ newCrc[4],
                                  x[0] ^ x[1] ^ x[3] ^ x[4] ^ newCrc[3],
                                  x[0] ^ x[2] ^ x[3] ^ x[5] ^ newCrc[2],
                                  x[1] ^ x[2] ^ x[4] ^ x[5] ^ newCrc[1],
                                  x[0] ^ x[1] ^ x[3] ^ x[4] ^ newCrc[0],
                                  x[0] ^ x[2] ^ x[3] ^ x[5] ^ x[7],
                                  x[1] ^ x[2] ^ x[4] ^ x[5] ^ x[6] ^ x[7],
                                  x[7] ^ x[6] ^ x[5] ^ x[4] ^ x[3] ^ x[1] ^ x[0],
                                  x[6] ^ x[4] ^ x[3] ^ x[2] ^ x[0],
                                  x[7] ^ x[1] ^ x[2] ^ x[3],
                                  x[6] ^ x[0] ^ x[7] ^ x[1] ^ x[2],
                                  x[6] ^ x[0] ^ x[7] ^ x[1],
                                  x[6] ^ x[0]});	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, vcrc32_8.scala:24:23, :28:23, :32:{18,22,25}, :33:{18,25,29,32}, :34:{18,25,36,39}, :35:{18,36,39}, :36:{25,43,46}, :37:{25,43,46}, :38:{29,32}, :39:{36,39}, :40:{36,39}, :41:{22,25}, :42:{22,25}, :43:{22,25}, :44:{29,32}, :45:{36,39}, :46:{36,39}, :47:{36,39}, :48:{43,46}, :49:{50,53}, :50:{57,60}, :51:{57,60}, :52:{43,46}, :53:{43,46}, :54:{43,46}, :55:{43,46}, :56:43, :57:50, :58:57, :59:43, :60:36, :61:43, :62:36, :63:22, :65:8, :74:18, :75:12, :76:23, :100:22, :104:{48,60,71}
  wire        _GEN_0 = crcReg == newCrc;	// vcrc32_8.scala:24:23, :74:18, :75:12, :76:23, :108:32
  CRC_should_remain_stable_when_clock_enable_is_false:
    assert property (@(posedge clock) disable iff (~hasBeenReset) io_clken | _GEN_0);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, vcrc32_8.scala:108:{21,32}
  Data_output_should_be_inverse_of_upper_8_bits_of_CRC:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(crcReg[31:24]) == ~(crcReg[31:24]));	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, vcrc32_8.scala:24:23, :90:{18,25}, :111:{24,28}
  CRC_OK_flag_should_match_CRC_remainder_comparison:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, vcrc32_8.scala:7:7
  CRC_output_should_match_internal_CRC_register:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, vcrc32_8.scala:7:7
  Load_and_compute_should_not_be_asserted_simultaneously:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     io_reset | ~(io_load & io_compute));	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, vcrc32_8.scala:120:{21,24,34}
  CRC_register_should_maintain_322Dbit_width:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, vcrc32_8.scala:7:7
  Data_input_should_maintain_82Dbit_width:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, vcrc32_8.scala:7:7
  CRC_should_be_stable_when_idle_28no_control_signals_active29:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     io_clken | io_reset | io_load | io_compute | _GEN_0);	// src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59, vcrc32_8.scala:108:32, :129:58
  always @(posedge clock) begin	// vcrc32_8.scala:7:7
    if (reset) begin	// vcrc32_8.scala:7:7
      hasBeenResetReg <= 1'h1;	// src/main/scala/chisel3/ltl/LTL.scala:362:39, vcrc32_8.scala:7:7
      crcReg <= 32'hFFFFFFFF;	// vcrc32_8.scala:24:23
    end
    else if (io_clken) begin	// vcrc32_8.scala:8:14
      if (io_reset)	// vcrc32_8.scala:8:14
        crcReg <= 32'hFFFFFFFF;	// vcrc32_8.scala:24:23
      else if (io_load)	// vcrc32_8.scala:8:14
        crcReg <= _newCrc_T_1;	// vcrc32_8.scala:24:23, :77:18
      else if (io_compute)	// vcrc32_8.scala:8:14
        crcReg <= _newCrc_T_2;	// vcrc32_8.scala:24:23, :65:8
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// vcrc32_8.scala:7:7
    `ifdef FIRRTL_BEFORE_INITIAL	// vcrc32_8.scala:7:7
      `FIRRTL_BEFORE_INITIAL	// vcrc32_8.scala:7:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// vcrc32_8.scala:7:7
      automatic logic [31:0] _RANDOM[0:0];	// vcrc32_8.scala:7:7
      `ifdef INIT_RANDOM_PROLOG_	// vcrc32_8.scala:7:7
        `INIT_RANDOM_PROLOG_	// vcrc32_8.scala:7:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// vcrc32_8.scala:7:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// vcrc32_8.scala:7:7
        crcReg = _RANDOM[/*Zero width*/ 1'b0];	// vcrc32_8.scala:7:7, :24:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// vcrc32_8.scala:7:7
      `FIRRTL_AFTER_INITIAL	// vcrc32_8.scala:7:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  assign io_data_out = ~(crcReg[31:24]);	// vcrc32_8.scala:7:7, :24:23, :90:{18,25}
  assign io_crc_ok = crcReg == 32'hC704DD7B;	// vcrc32_8.scala:7:7, :24:23, :91:23
  assign io_crc = crcReg;	// vcrc32_8.scala:7:7, :24:23
endmodule


// ----- 8< ----- FILE "./ResetCounter.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.1

module ResetCounter(
    input clk,
    input reset,
    output [31:0] timeSinceReset,
    output notChaos
);

reg [31:0] count;
reg flag;
initial begin
  count = 0;
  flag = 0;
end

assign timeSinceReset = count;
assign notChaos = flag;

always @(posedge clk) begin
    if (reset) begin
        count <= 0;
        flag <= 1;
    end else if (flag) begin
        count <= count + 1;
    end
end

endmodule
    

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----
