// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module ResetCounter

module gray(	// gray.scala:6:7
  input  clock,	// gray.scala:6:7
         reset,	// gray.scala:6:7
         io_i,	// gray.scala:7:14
  output io_z	// gray.scala:7:14
);

  reg        p;	// gray.scala:13:18
  reg        q;	// gray.scala:14:18
  reg        r;	// gray.scala:15:18
  wire       io_z_0 = p ^ q ^ r;	// gray.scala:13:18, :14:18, :15:18, :27:13
  reg        hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire       hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// gray.scala:6:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  Output_z_should_equal_register_r:
    assert property (@(posedge clock) disable iff (~hasBeenReset) io_z_0 == r);	// gray.scala:15:18, :27:13, :32:17, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Wire_w_should_be_p_XOR_q:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// gray.scala:6:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Output_z_should_be_w_XOR_r:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1);	// gray.scala:6:7, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Register_q_should_get_previous_p_value:
    assert property (@(posedge clock) disable iff (~hasBeenReset) q == p);	// gray.scala:13:18, :14:18, :44:32, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Register_r_should_get_previous_io_z_value:
    assert property (@(posedge clock) disable iff (~hasBeenReset) r == io_z_0);	// gray.scala:15:18, :27:13, :48:32, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Register_p_should_get_io_i_value:
    assert property (@(posedge clock) disable iff (~hasBeenReset) p == io_i);	// gray.scala:13:18, :52:32, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire [2:0] _GEN = {io_i, p, q};	// gray.scala:13:18, :14:18, :56:35
  reg  [2:0] r_1;	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Delay.scala:11:20
  When_input_is_stable2C_state_should_follow_expected_pattern:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     io_i != p | _GEN == r_1);	// gray.scala:13:18, :56:{19,25,35}, home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Delay.scala:11:20, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// gray.scala:6:7
    if (reset) begin	// gray.scala:6:7
      hasBeenResetReg <= 1'h1;	// gray.scala:6:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
      p <= 1'h0;	// gray.scala:6:7, :13:18
      q <= 1'h0;	// gray.scala:6:7, :14:18
      r <= 1'h0;	// gray.scala:6:7, :15:18
    end
    else begin	// gray.scala:6:7
      p <= io_i;	// gray.scala:13:18
      q <= p;	// gray.scala:13:18, :14:18
      r <= io_z_0;	// gray.scala:15:18, :27:13
    end
    r_1 <= _GEN;	// gray.scala:56:35, home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Delay.scala:11:20
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// gray.scala:6:7
    `ifdef FIRRTL_BEFORE_INITIAL	// gray.scala:6:7
      `FIRRTL_BEFORE_INITIAL	// gray.scala:6:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// gray.scala:6:7
      automatic logic [31:0] _RANDOM[0:0];	// gray.scala:6:7
      `ifdef INIT_RANDOM_PROLOG_	// gray.scala:6:7
        `INIT_RANDOM_PROLOG_	// gray.scala:6:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// gray.scala:6:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// gray.scala:6:7
        p = _RANDOM[/*Zero width*/ 1'b0][0];	// gray.scala:6:7, :13:18
        q = _RANDOM[/*Zero width*/ 1'b0][1];	// gray.scala:6:7, :13:18, :14:18
        r = _RANDOM[/*Zero width*/ 1'b0][2];	// gray.scala:6:7, :13:18, :15:18
        r_1 = _RANDOM[/*Zero width*/ 1'b0][8:6];	// gray.scala:6:7, :13:18, home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Delay.scala:11:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// gray.scala:6:7
      `FIRRTL_AFTER_INITIAL	// gray.scala:6:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  assign io_z = io_z_0;	// gray.scala:6:7, :27:13
endmodule


// ----- 8< ----- FILE "./ResetCounter.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.1

module ResetCounter(
    input clk,
    input reset,
    output [31:0] timeSinceReset,
    output notChaos
);

reg [31:0] count;
reg flag;
initial begin
  count = 0;
  flag = 0;
end

assign timeSinceReset = count;
assign notChaos = flag;

always @(posedge clk) begin
    if (reset) begin
        count <= 0;
        flag <= 1;
    end else if (flag) begin
        count <= count + 1;
    end
end

endmodule
    

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----
