// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module ResetCounter

module b01(	// b01.scala:11:7
  input  clock,	// b01.scala:11:7
         reset,	// b01.scala:11:7
         io_LINE1,	// b01.scala:12:14
         io_LINE2,	// b01.scala:12:14
  output io_OUTP,	// b01.scala:12:14
         io_OVERFLW	// b01.scala:12:14
);

  reg  [2:0] stato;	// b01.scala:20:22
  reg        outpReg;	// b01.scala:23:24
  reg        overflwReg;	// b01.scala:24:27
  wire       _GEN = stato == 3'h3;	// b01.scala:20:22, :31:17, :70:15
  wire       _GEN_0 = stato == 3'h1;	// b01.scala:20:22, :31:17, :36:15
  wire       _GEN_1 = stato == 3'h4;	// b01.scala:20:22, :31:17, :34:15
  wire       _GEN_2 = stato == 3'h2;	// b01.scala:20:22, :31:17, :54:15
  wire       _GEN_3 = stato == 3'h5;	// b01.scala:20:22, :31:17, :52:15
  wire       _GEN_4 = stato == 3'h6;	// b01.scala:20:22, :31:17, :72:15
  wire       _GEN_5 = _GEN_4 | (&stato);	// b01.scala:20:22, :24:27, :31:17, :93:18, :102:18
  reg        hasBeenResetReg;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  initial	// src/main/scala/chisel3/ltl/LTL.scala:362:39
    hasBeenResetReg = 1'bx;	// src/main/scala/chisel3/ltl/LTL.scala:362:39
  wire       hasBeenReset = hasBeenResetReg === 1'h1 & reset === 1'h0;	// b01.scala:11:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
  OVERFLW_should_only_be_true_in_state_e:
    assert property (@(posedge clock) disable iff (~hasBeenReset) _GEN | ~overflwReg);	// b01.scala:24:27, :31:17, :109:{33,36}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  State_should_be_one2Dhot_encoded:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     {1'h0, stato[0]} + {1'h0, stato[1]} + {1'h0, stato[2]} == 2'h1);	// b01.scala:11:7, :20:22, :113:15, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire       _GEN_6 = _GEN_0 | _GEN_1;	// b01.scala:31:17, :116:58
  From_state_a2C_next_state_should_be_b_or_f:
    assert property (@(posedge clock) disable iff (~hasBeenReset) (|stato) | _GEN_6);	// b01.scala:20:22, :31:17, :116:{33,58}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  From_state_e2C_next_state_should_be_b_or_f:
    assert property (@(posedge clock) disable iff (~hasBeenReset) stato != 3'h3 | _GEN_6);	// b01.scala:20:22, :70:15, :116:58, :120:{18,33}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire       _GEN_7 = _GEN_2 | _GEN_3;	// b01.scala:31:17, :124:58
  From_state_b2C_next_state_should_be_c_or_g:
    assert property (@(posedge clock) disable iff (~hasBeenReset) stato != 3'h1 | _GEN_7);	// b01.scala:20:22, :36:15, :124:{18,33,58}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  From_state_c2C_next_state_should_be_e_or_wf0:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     stato != 3'h2 | _GEN | _GEN_4);	// b01.scala:20:22, :31:17, :54:15, :128:{18,33}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  From_state_f2C_next_state_should_be_c_or_g:
    assert property (@(posedge clock) disable iff (~hasBeenReset) stato != 3'h4 | _GEN_7);	// b01.scala:20:22, :34:15, :124:58, :132:{18,33}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  From_state_g2C_next_state_should_be_wf0_or_wf1:
    assert property (@(posedge clock) disable iff (~hasBeenReset) stato != 3'h5 | _GEN_5);	// b01.scala:20:22, :24:27, :31:17, :52:15, :93:18, :102:18, :136:{18,33}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire       _GEN_8 = ~(|stato) | _GEN;	// b01.scala:20:22, :31:17, :140:60
  From_state_wf02C_next_state_should_be_a_or_e:
    assert property (@(posedge clock) disable iff (~hasBeenReset) stato != 3'h6 | _GEN_8);	// b01.scala:20:22, :72:15, :140:{18,35,60}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  From_state_wf12C_next_state_should_be_a_or_e:
    assert property (@(posedge clock) disable iff (~hasBeenReset) ~(&stato) | _GEN_8);	// b01.scala:20:22, :31:17, :140:60, :144:{18,35}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  wire       _GEN_9 = io_LINE1 ^ io_LINE2;	// b01.scala:152:80
  In_XOR_states2C_OUTP_should_equal_LINE1_XOR_LINE2:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(~(|stato) | _GEN_0 | _GEN_2 | _GEN | _GEN_4) | outpReg == _GEN_9);	// b01.scala:20:22, :23:24, :31:17, :152:{12,49,55,66,80}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  In_NXOR_states2C_OUTP_should_equal_NOT28LINE1_XOR_LINE229:
    assert property (@(posedge clock) disable iff (~hasBeenReset)
                     ~(_GEN_1 | _GEN_3 | (&stato)) | outpReg == ~_GEN_9);	// b01.scala:20:22, :23:24, :31:17, :152:80, :155:{12,50,56,67,71}, src/main/scala/chisel3/ltl/LTL.scala:321:32, :333:34, :362:39, :431:59
  Should_eventually_return_to_state_a:
    assert property (@(posedge clock) disable iff (~hasBeenReset) 1'h1 |-> ##[1:20]
                     ~(|stato));	// b01.scala:11:7, :20:22, :31:17, src/main/scala/chisel3/ltl/LTL.scala:125:32, :262:38, :321:32, :333:34, :362:39, :431:59
  always @(posedge clock) begin	// b01.scala:11:7
    if (reset) begin	// b01.scala:11:7
      hasBeenResetReg <= 1'h1;	// b01.scala:11:7, src/main/scala/chisel3/ltl/LTL.scala:362:39
      stato <= 3'h0;	// b01.scala:20:22, :90:15
      outpReg <= 1'h0;	// b01.scala:11:7, :23:24
      overflwReg <= 1'h0;	// b01.scala:11:7, :24:27
    end
    else begin	// b01.scala:11:7
      automatic logic       _GEN_10;	// b01.scala:33:21
      automatic logic [2:0] _GEN_11;	// b01.scala:33:33, :34:15, :36:15
      _GEN_10 = io_LINE1 & io_LINE2;	// b01.scala:33:21
      _GEN_11 = _GEN_10 ? 3'h4 : 3'h1;	// b01.scala:33:{21,33}, :34:15, :36:15
      if (|stato) begin	// b01.scala:20:22, :31:17
        automatic logic            _GEN_12 = io_LINE1 | io_LINE2;	// b01.scala:60:21
        automatic logic [7:0][2:0] _GEN_13;	// b01.scala:20:22, :31:17, :42:33, :51:33, :60:33, :69:33, :78:33, :87:33, :96:33
        automatic logic [7:0]      _GEN_14;	// b01.scala:23:24, :31:17, :47:15, :56:15, :65:15, :74:15, :83:15, :92:15, :101:15
        _GEN_13 =
          {{_GEN_12 ? 3'h3 : 3'h0},
           {_GEN_10 ? 3'h3 : 3'h0},
           {{2'h3, _GEN_12}},
           {_GEN_12 ? 3'h5 : 3'h2},
           {_GEN_11},
           {_GEN_10 ? 3'h3 : 3'h6},
           {_GEN_10 ? 3'h5 : 3'h2},
           {stato}};	// b01.scala:20:22, :31:17, :33:{21,33}, :34:15, :36:15, :42:33, :51:33, :52:15, :54:15, :60:{21,33}, :61:15, :63:15, :69:33, :70:15, :72:15, :78:33, :79:15, :81:15, :87:33, :88:15, :90:15, :96:33, :97:15, :99:15
        stato <= _GEN_13[stato];	// b01.scala:20:22, :31:17, :42:33, :51:33, :60:33, :69:33, :78:33, :87:33, :96:33
        _GEN_14 =
          {{io_LINE1 ^ ~io_LINE2},
           {io_LINE1 ^ io_LINE2},
           {io_LINE1 ^ ~io_LINE2},
           {io_LINE1 ^ ~io_LINE2},
           {io_LINE1 ^ io_LINE2},
           {io_LINE1 ^ io_LINE2},
           {io_LINE1 ^ io_LINE2},
           {outpReg}};	// b01.scala:23:24, :31:17, :47:{15,27}, :56:{15,27}, :65:{15,18}, :74:{15,27}, :83:{15,18}, :92:{15,27}, :101:{15,18}
        outpReg <= _GEN_14[stato];	// b01.scala:20:22, :23:24, :31:17, :47:15, :56:15, :65:15, :74:15, :83:15, :92:15, :101:15
      end
      else begin	// b01.scala:31:17
        stato <= _GEN_11;	// b01.scala:20:22, :33:33, :34:15, :36:15
        outpReg <= io_LINE1 ^ io_LINE2;	// b01.scala:23:24, :38:27
      end
      overflwReg <=
        (|stato) & (_GEN | ~(_GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_5) & overflwReg);	// b01.scala:20:22, :24:27, :31:17, :39:18, :48:18, :57:18, :66:18, :75:18, :84:18, :93:18, :102:18
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// b01.scala:11:7
    `ifdef FIRRTL_BEFORE_INITIAL	// b01.scala:11:7
      `FIRRTL_BEFORE_INITIAL	// b01.scala:11:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// b01.scala:11:7
      automatic logic [31:0] _RANDOM[0:0];	// b01.scala:11:7
      `ifdef INIT_RANDOM_PROLOG_	// b01.scala:11:7
        `INIT_RANDOM_PROLOG_	// b01.scala:11:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// b01.scala:11:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// b01.scala:11:7
        stato = _RANDOM[/*Zero width*/ 1'b0][2:0];	// b01.scala:11:7, :20:22
        outpReg = _RANDOM[/*Zero width*/ 1'b0][3];	// b01.scala:11:7, :20:22, :23:24
        overflwReg = _RANDOM[/*Zero width*/ 1'b0][4];	// b01.scala:11:7, :20:22, :24:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// b01.scala:11:7
      `FIRRTL_AFTER_INITIAL	// b01.scala:11:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetCounter resetCounter (	// home/chenty/llm/TileLinkLLM/chisel/chiselfv/src/main/scala/chiselFv/Formal.scala:12:36
    .clk            (clock),
    .reset          (reset),
    .timeSinceReset (/* unused */),
    .notChaos       (/* unused */)
  );
  assign io_OUTP = outpReg;	// b01.scala:11:7, :23:24
  assign io_OVERFLW = overflwReg;	// b01.scala:11:7, :24:27
endmodule


// ----- 8< ----- FILE "./ResetCounter.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.1

module ResetCounter(
    input clk,
    input reset,
    output [31:0] timeSinceReset,
    output notChaos
);

reg [31:0] count;
reg flag;
initial begin
  count = 0;
  flag = 0;
end

assign timeSinceReset = count;
assign notChaos = flag;

always @(posedge clk) begin
    if (reset) begin
        count <= 0;
        flag <= 1;
    end else if (flag) begin
        count <= count + 1;
    end
end

endmodule
    

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----
